using NSubstitute;

namespace UniversalNFT.dev.API.Tests.Services.Rules
{
    // For the first 1-49 projects we test them each individually as that is a large
    // spread of the XRPL NFTs including checking we can get the metadata by using the 
    // actual Token.URI format.
    // For 50+ we don't check the Token.URI format and just validate the metadata json
    // as its quite likely there won't be further variation.
    // Any reported variation in Token.URI would be worthy of its own test, if found.
    public class _50To_99Tests : BaseRuleTest
    {
        [TestCase("legoxpunks", "ipfs://bafybeicaur7ie7lrupnxekqakqh3u2rasvlrddwwoncbaah2fjjltziesa/1678663286906.png", @"{""attributes"":[{""description"":""1-background"",""trait_type"":""1-background"",""value"":""turquoise""},{""description"":""2-skin"",""trait_type"":""2-skin"",""value"":""lightandbrown""},{""description"":""3-frame"",""trait_type"":""3-frame"",""value"":""frame""},{""description"":""4-beard"",""trait_type"":""4-beard"",""value"":""blondy""},{""description"":""5-eyes"",""trait_type"":""5-eyes"",""value"":""close""},{""description"":""6-wearing"",""trait_type"":""6-wearing"",""value"":""blank""},{""description"":""7-mouth"",""trait_type"":""7-mouth"",""value"":""boring""},{""description"":""8-glass"",""trait_type"":""8-glass"",""value"":""blank""},{""description"":""9-accessories"",""trait_type"":""9-accessories"",""value"":""longandsilverandearing""}],""collection"":{""name"":""legoxpunks"",""family"":""Legoxpunks""},""video"":"""",""animation"":"""",""external_link"":"""",""audio"":"""",""name"":""LegoXpunk #3411"",""image"":""ipfs://bafybeicaur7ie7lrupnxekqakqh3u2rasvlrddwwoncbaah2fjjltziesa/1678663286906.png"",""taxon"":8566,""description"":""Lego created Punks on the XRPL"",""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""id"":""714811d10bc2a863ad5817e6ac16441a:1678663286739"",""file"":""""}")]

        [TestCase("CelestialSpirits", "ipfs://bafybeic4ometrb53smtc5tz54uxt4j6hfnfe7bnksbhzmrldhtq3ejtmlm/blob", @"{""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""name"":""#1985"",""description"":""Celeastial Spirits by MoonWorld"",""collection"":{""name"":""Celestial Spirits"",""family"":""Celestial Spirits""},""attributes"":[{""trait_type"":""Background"",""value"":""Leo""},{""trait_type"":""01 Planet"",""value"":""Sun""},{""trait_type"":""03 Body"",""value"":""White""},{""trait_type"":""04 Clothes"",""value"":""Molten Core Suit""},{""trait_type"":""05 Eyes"",""value"":""Peridot""},{""trait_type"":""06 Mouth"",""value"":""Mask - Grey""},{""trait_type"":""07 Headwear"",""value"":""Dynasty - Purple""},{""trait_type"":""08 Hand"",""value"":""Fire - Blue""}],""image"":""ipfs://bafybeic4ometrb53smtc5tz54uxt4j6hfnfe7bnksbhzmrldhtq3ejtmlm/blob""}")]

        [TestCase("3DAPE", "ipfs://bafybeiftm3ctuuodjh6k2tsju2vvg5wih7srv47723hph7dbh3njwf6fvm/7238.png", @"{ ""name"": ""3DAPE #7238"", ""image"": ""ipfs://bafybeiftm3ctuuodjh6k2tsju2vvg5wih7srv47723hph7dbh3njwf6fvm/7238.png"", ""collection"": { ""name"": ""3DAPES"", ""description"": ""3DAPES are the highest quality, 3D Modelled NFTs on the XRPL. A collection of 10,000 unique character designs, with over 800 defining traits and thousands of variations. 'The 3DAPES were designed meticulously to be the best of the best, only for the XRP Ledger' - \u03b1lpha\u03a9mega"", ""image"": ""ipfs://bafkreicnagovzhd22b6qezf7pzvptmbgvfsuwtjc6s3fwy3pmbgkzuxnoq"" }, ""attributes"": [ { ""trait_type"": ""Accessories"", ""value"": ""AK47"" }, { ""trait_type"": ""Earrings"", ""value"": ""Skull & Bones Earring"" }, { ""trait_type"": ""Eyes"", ""value"": ""Gold Eyes"" }, { ""trait_type"": ""Facial Expressions"", ""value"": ""Growl Beige"" }, { ""trait_type"": ""Fur With Hair"", ""value"": ""Black Fur With Short Hair"" }, { ""trait_type"": ""Headware"", ""value"": ""No Headware"" }, { ""trait_type"": ""Long Collar & Hooded"", ""value"": ""No Hood"" }, { ""trait_type"": ""Nose Rings"", ""value"": ""Nose Ring Black"" }, { ""trait_type"": ""Shirts"", ""value"": ""No Shirt"" }, { ""trait_type"": ""Tattoos"", ""value"": ""No Tattoo"" }, { ""trait_type"": ""Vests"", ""value"": ""No Vest"" }]}")]

        [TestCase("Teddy Games", "ipfs://bafybeick3t46ntq5jbnbyx6rh7vztuz4rfbja2eoxotllnthfuievtgalu/70.png", @"{""schema"":""ipfs://bafkreicb4oll55hjdog5jd6tkoinkfrfx57yva3om4pcxeubbi4ybxjwxy"",""nftType"":""nftmaster.v0"",""name"":""Teddy Games #70"",""category"":""collectibles"",""description"":""Dr. Dvs Workshop and the Terror Teddies present the Teddy Games NFT Collection. This is a Champions only collection of 99 PFPs, reserved soley for those most worthy. A unique opportunity presented by a ground breaking collection that offers immutable and transferable commercial IP rights to its owners. This NFT is the first of its kind, allowing 99 people the rights to use the Terror Teddies skull face logo with an immutable IPFS stored NFT license built directly into the NFT properties, and verifiable proof of ownership on the XRP Ledger. NFT License: https://nftstorage.link/ipfs/bafybeigj5nibum7b6xglpn5svedy7fhxgnuhuovyqwqjqh26be66obccg4"",""image"":""ipfs://bafybeick3t46ntq5jbnbyx6rh7vztuz4rfbja2eoxotllnthfuievtgalu/70.png"",""video"":null,""animation"":null,""audio"":null,""file"":null,""external_link"":null,""location"":null,""collection"":{""name"":""Terror Games"",""family"":""Dr. Dvs Workshop and the Terror Teddies present the Teddy Games NFT Collection.""},""attributes"":[{""name"":""Background"",""value"":""Dark Cyan""},{""name"":""Fur"",""value"":""Caesar""},{""name"":""Accessories"",""value"":""pipe""},{""name"":""Head"",""value"":""Visitor""},{""name"":""Eyes"",""value"":""Eye Patch""},{""name"":""Teddy_Games"",""value"":""Round 4 Survivor""},{""name"":""NFT_License"",""value"":""https://nftstorage.link/ipfs/bafybeigj5nibum7b6xglpn5svedy7fhxgnuhuovyqwqjqh26be66obccg4""}]}")]

        [TestCase("PAWNKING SERIES", "ipfs://QmaUuGFzJQ1Lf1yyuiNWR3GLz8nY83GSpQe24WjMT2mcsP", @"{""name"":""OTTOMAN - TURKEY#06"",""description"":""As a bridge between East and West, the Ottoman Empire connected diverse cultures and civilizations. This vibrant exchange emerged a rich tapestry of art, cuisine, architectures, and traditions that still thrive in modern societies."",""collection"":{""name"":""PAWNKING SERIES""},""attributes"":[{""trait_type"":""Frame"",""value"":""Brown Wall Ornament""},{""trait_type"":""Circle - S"",""value"":""Middle East Blue - Gold Ceiling""},{""trait_type"":""Circle - M"",""value"":""Blue""},{""trait_type"":""Circle - L"",""value"":""Brown Ceilings""},{""trait_type"":""King - Background Left"",""value"":""White Pole Building""},{""trait_type"":""King - Background Top"",""value"":""Bronze Circular Ceiling - Eye Nights""},{""trait_type"":""King - Bacground"",""value"":""Blue White Vintage Flowery""},{""trait_type"":""Pawn - Background Right"",""value"":""Eye Nights V2""},{""trait_type"":""Pawn - Background Low"",""value"":""Dark Gold Dome Ceiling V2""},{""trait_type"":""Pawn - Background"",""value"":""Blue White Vintage Flowery""},{""trait_type"":""King - Turban"",""value"":""Brown Turban - Brown""},{""trait_type"":""King - Stick"",""value"":""Gold Stick""},{""trait_type"":""King - Fur Coat"",""value"":""Cream - White - Red Coat""},{""trait_type"":""King - Hair"",""value"":""Dark Brown""},{""trait_type"":""King - Head"",""value"":""White Skin""},{""trait_type"":""Pawn - Hair"",""value"":""Dark Brown""},{""trait_type"":""Pawn - Stick"",""value"":""Gold Stick""},{""trait_type"":""Pawn - Shirt"",""value"":""Black Shirt""},{""trait_type"":""Pawn - Head"",""value"":""White Skin""},{""trait_type"":""Pawn - Hat"",""value"":""Ruby Hat""},{""trait_type"":""Share Revenue"",""value"":""0.0002""}],""image"":""ipfs://QmaUuGFzJQ1Lf1yyuiNWR3GLz8nY83GSpQe24WjMT2mcsP""}")]

        [TestCase("RipplePunk Rewind", "ipfs://bafybeihl2xslyvr3zljogtgdizemb7uk4l5jbqhvfonjq3pcqxg35ol4zy/1689194892056.gif", @"{""attributes"":[{""description"":""Color"",""trait_type"":""Color"",""value"":""Blue""},{""description"":""Type"",""trait_type"":""Type"",""value"":""Male""},{""description"":""Accessory"",""trait_type"":""Accessory"",""value"":""3 Attributes""},{""description"":""Accessory"",""trait_type"":""Accessory"",""value"":""Peak Spike""},{""description"":""Accessory"",""trait_type"":""Accessory"",""value"":""Goat""},{""description"":""Accessory"",""trait_type"":""Accessory"",""value"":""VR""}],""collection"":{""name"":""RipplePunks Rewind"",""family"":""Family NFTs""},""video"":"""",""animation"":""ipfs://bafybeihl2xslyvr3zljogtgdizemb7uk4l5jbqhvfonjq3pcqxg35ol4zy/1689194892056.gif"",""external_link"":"""",""audio"":"""",""name"":""RipplePunk Rewind #9694"",""image"":"""",""taxon"":48919,""description"":""Reviving the RipplePunks, pixel by pixel, by animating and meticulously reconstructing their digital existence."",""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""id"":""f69bd5809770109770084efbc3aa37f6:1689194892026"",""file"":""""}")]

        [TestCase("hOOters", "ipfs://bafybeia6y7dzo7m6zqx5qigglel6etre5opy52brttslxndpzbt6jodrk4/1676418730570.png", @"{""attributes"":[{""description"":""Background"",""trait_type"":""Background"",""value"":""Light Green""},{""description"":""Skins"",""trait_type"":""Skins"",""value"":""Purple""},{""description"":""Head"",""trait_type"":""Head"",""value"":""Bucket""},{""description"":""Glasses"",""trait_type"":""Glasses"",""value"":""Gold Pink""},{""description"":""Clothing"",""trait_type"":""Clothing"",""value"":""Red Jacket""},{""description"":""Mouth"",""trait_type"":""Mouth"",""value"":""Pout""},{""description"":""Extras"",""trait_type"":""Extras"",""value"":""Heart""}],""collection"":{""name"":""hOOters"",""family"":""Club OOtopia""},""video"":"""",""animation"":"""",""external_link"":"""",""audio"":"""",""name"":""hOOters #2695"",""image"":""ipfs://bafybeia6y7dzo7m6zqx5qigglel6etre5opy52brttslxndpzbt6jodrk4/1676418730570.png"",""taxon"":5584,""description"":""5K hOOters on the XRPL"",""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""id"":""376dbfd7f1e1dc9fe370d63e38ac2065:1676418730460"",""file"":""""}")]

        [TestCase("1st Gen", "ipfs://QmQEgmjgmdNiMdtDFXQCCmR7SG7LqJAfn6m2zM4GPsHpqH/535.png", @"{ ""dna"": ""d2487c2fa0d9732aa51ec61dd80529a1afcec7db"", ""name"": ""#535"", ""description"": ""1 Xpossum NFT/9696 by XRPL Awesome Possum. Made in Canada"", ""image"": ""ipfs://QmQEgmjgmdNiMdtDFXQCCmR7SG7LqJAfn6m2zM4GPsHpqH/535.png"", ""edition"": 535, ""date"": 1667149250385, ""collection"": { ""family"": ""Xpossum 2022"", ""name"": ""1st Gen"" }, ""artist"": ""C. Goretski"", ""attributes"": [ { ""trait_type"": ""BG Colour"", ""value"": ""Forest Path"" }, { ""trait_type"": ""Background"", ""value"": ""Blank"" }, { ""trait_type"": ""Main Body"", ""value"": ""Brown Possum"" }, { ""trait_type"": ""Mouth"", ""value"": ""Xapes Chain"" }, { ""trait_type"": ""Eyes"", ""value"": ""Blank"" }, { ""trait_type"": ""Hair"", ""value"": ""Top Hat"" }, { ""trait_type"": ""Hand"", ""value"": ""Watch Gold"" } ], ""compiler"": ""HashLips Art Engine"" }")]

        [TestCase("Rich Ducks Crypto Club", "ipfs://bafybeih3fio2wjtr2daszvziisjpaaympyvfigrxcy4pnhjbkjqqwpo5y4/3735.png", @"{ ""schema"": ""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"", ""nftType"": ""art.v0"", ""name"": ""Rich Duck #3735"", ""description"": ""Welcome to the Rich Ducks Crypto Club! These filthy Rich Ducks led by the 'Moon Commander' XRP Bags. All 10K Rich Ducks are hand drawn and randomly generated with over 200 traits curated by ClubXRPL. Holding one of these NFTs will give you access to the Rich Duck Crypto Club, whitelist, discounts, music perks and much more. See you at the tippy top!"", ""image"": ""ipfs://bafybeih3fio2wjtr2daszvziisjpaaympyvfigrxcy4pnhjbkjqqwpo5y4/3735.png"", ""image_url"": ""ipfs://bafybeih3fio2wjtr2daszvziisjpaaympyvfigrxcy4pnhjbkjqqwpo5y4/3735.png"", ""category"": ""art"", ""content_type"": ""image/png"", ""collection"": { ""name"": ""Rich Ducks Crypto Club"" }, ""attributes"": [ { ""trait_type"": ""Background"", ""value"": ""Piles Of Gold"" }, { ""trait_type"": ""Body"", ""value"": ""Silver"" }, { ""trait_type"": ""Shoes"", ""value"": ""None"" }, { ""trait_type"": ""Clothes"", ""value"": ""Military Uniform"" }, { ""trait_type"": ""Necklace"", ""value"": ""None"" }, { ""trait_type"": ""Mouth"", ""value"": ""Normal"" }, { ""trait_type"": ""Left Hand"", ""value"": ""Orgone Pyramid Ripple"" }, { ""trait_type"": ""Right Hand"", ""value"": ""Rose Gold Watch"" }, { ""trait_type"": ""Rings"", ""value"": ""XRP"" }, { ""trait_type"": ""Eyes"", ""value"": ""Normal"" }, { ""trait_type"": ""Eyewear"", ""value"": ""Daft Punk"" }, { ""trait_type"": ""Hats"", ""value"": ""None"" } ], ""external_url"": ""https://xrpbags.io"", ""edition"": 3735, ""date"": 1668556800000, ""compiler"": ""metaleet"" }")]

        [TestCase("Magnetic Girls", "ipfs://ipfs/bafybeifiyhket5kv2scvmpw33wh6nfzq3svmis67b7yf2zokmmk5v5yh54/image.jpeg", @"{""name"":""Common | S2#71"",""description"":""Magnetic Girl Common | S2#71\n\nGirls provide incredible benefits in mining and other Magnetic tools! Trade and Mine with Magnetic Girls."",""external_url"":""https://xmagnetic.org"",""attributes"":[{""trait_type"":""rarity"",""value"":""Common""}],""category"":""others"",""md5hash"":""7165fc9926eb56177c13c9d3407e1b85"",""is_explicit"":false,""content_type"":""image/png"",""image_url"":""ipfs://ipfs/bafybeifiyhket5kv2scvmpw33wh6nfzq3svmis67b7yf2zokmmk5v5yh54/image.jpeg"",""animation_url"":""ipfs://ipfs/bafybeifiyhket5kv2scvmpw33wh6nfzq3svmis67b7yf2zokmmk5v5yh54/animation.png""}")]

        [TestCase("xPEPE", "QmUoqwgAq5mFuj4hYn1mnnRyHdW8AqQJ9vSUkKb56q2fx9/4442.png", @"{""name"":""xPEPE #4442"",""description"":""xPEPE vol 1 - An XRPL community collection of 5,000 generative xPEPEs - Minted on xrpnft.com - Art by Link"",""fee_recipient"":""r3gpBgxueWCDkH9985UzrB1Pt9DhLC8ATz"",""seller_fee_basis_points"":589,""image"":""QmUoqwgAq5mFuj4hYn1mnnRyHdW8AqQJ9vSUkKb56q2fx9/4442.png"",""external_url"":"""",""attributes"":[{""trait_type"":""Background"",""value"":""Background Stars Black Green""},{""trait_type"":""Base"",""value"":""Base Tattoo 589""},{""trait_type"":""Eye"",""value"":""Eyes Wide Monocle""},{""trait_type"":""Hat"",""value"":""Hat Pope""},{""trait_type"":""Shirt"",""value"":""Shirt Teal""},{""trait_type"":""Mouth"",""value"":""Mouth Cringe""},{""trait_type"":""Nose"",""value"":""Nose Piggy""},{""trait_type"":""Shoulder"",""value"":""Shoulder Spike Blue""}],""hash"":""2233f0cc5fc0101afe0ff153374d1c9d"",""external_link"":""xrpepe.com"",""category"":""Art"",""collection"":{""name"":""xPEPE""}}")]

        [TestCase("X Baes", "ipfs://QmSvXDW2X8ZCP6H2LNRKSzZcZyDouE7TLAjQZCE7KY1QJE", @"{""name"":""Bae #3034"",""description"":""The Club X Baes are a female themed generative art collection paying homage to XRP lore and legendary ladies. Portion of royalties goes to support women's charities"",""image"":""ipfs://QmSvXDW2X8ZCP6H2LNRKSzZcZyDouE7TLAjQZCE7KY1QJE"",""dna"":""12240922d6560ae6865ec1522844395e3b448e86"",""edition"":3034,""date"":1663565778295,""attributes"":[{""trait_type"":""Background"",""value"":""Black""},{""trait_type"":""Wings"",""value"":""None""},{""trait_type"":""AlienSkinSmall"",""value"":""Small Alien Green""},{""trait_type"":""Tattoos"",""value"":""Heart Outline""},{""trait_type"":""AlienEyes"",""value"":""AlienEyes""},{""trait_type"":""Mouth"",""value"":""Full Plump Bubble Gum Pink""},{""trait_type"":""Face Jewelry"",""value"":""Nose Stud""},{""trait_type"":""Eyebrows"",""value"":""High Arch ""},{""trait_type"":""SmallClothes"",""value"":""Small Basic T LDN Pink""},{""trait_type"":""Necklace"",""value"":""Key""},{""trait_type"":""Hair"",""value"":""Hair Glow Super Rare""},{""trait_type"":""EyeWear"",""value"":""None""},{""trait_type"":""Earrings"",""value"":""None""},{""trait_type"":""Hat"",""value"":""None""},{""trait_type"":""Jacket"",""value"":""None""}],""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""collection"":{""name"":""X Baes"",""description"":""The 'XBAES' are a female influenced XRP themed art collectible created on the XRP Ledger. Only 6900 Baes will be available, with 100 legendary ladies and 6800 randomly generated Baes. Over 150 unique, hand drawn traits make up the the generations with each Bae being unique. Good Baes, Bad Baes, Humans, Cyborgs, Aliens, there's a special Bae out the in the cryptoverse for everyone!\n""},""external_url"":""www.clubxrpl.com""}")]
        
        [TestCase("RipplePunks Quartet", "ipfs://bafybeihyurttudul5j4ui67bjofpywcn3wep44erytjouvixx5rcvmlmwi/1680297325725.png", @"{""attributes"":[{""description"":""Type"",""trait_type"":""Type"",""value"":""Male""},{""description"":""Attribute"",""trait_type"":""Attribute"",""value"":""Front Beard Dark""},{""description"":""Quartet"",""trait_type"":""Quartet"",""value"":""Male - Front Beard Dark""},{""description"":""Ripple Punk"",""trait_type"":""Ripple Punk"",""value"":7330}],""collection"":{""name"":""RipplePunks Quartet"",""family"":""Family NFTs""},""video"":"""",""animation"":"""",""external_link"":"""",""audio"":"""",""name"":""RipplePunk Quartet #52"",""image"":""ipfs://bafybeihyurttudul5j4ui67bjofpywcn3wep44erytjouvixx5rcvmlmwi/1680297325725.png"",""taxon"":23578,""description"":""This quartet card belongs to the Male / Front Beard Dark series. \\nThere are 3 other cards that share the same type and attribute.\\nIf you hold all 4 quartet cards you will get 10 royalties points per day."",""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""id"":""3f403033e0b2e92ae3b89bd87ba7d786:1680297325697"",""file"":""""}")]
        
        [TestCase("XElon", "ipfs://QmbKMv8EtY4KzUGT8ssFPJzKKEtH3EC3J1cPxpYcnV23pZ?filename=QmbKMv8EtY4KzUGT8ssFPJzKKEtH3EC3J1cPxpYcnV23pZ", @"{""attributes"":[],""collection"":{""name"":""XElon"",""family"":""XElon""},""video"":"""",""animation"":"""",""external_link"":"""",""audio"":"""",""name"":""XElon #284"",""image"":""ipfs://QmbKMv8EtY4KzUGT8ssFPJzKKEtH3EC3J1cPxpYcnV23pZ?filename=QmbKMv8EtY4KzUGT8ssFPJzKKEtH3EC3J1cPxpYcnV23pZ"",""taxon"":39,""description"":"""",""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""id"":""f2424366bfba29786e74a23467041e95:1673296205788"",""file"":""""}")]
        
        [TestCase("XWX", "ipfs://ipfs/bafybeiggmne3egr423wzknxldnjtzvn5u5gxp7hcsiumlouvnztc5ffcru/image.jpeg", @"{""name"":""XWX 0143"",""description"":""This NFT was sold as part of The Second Gen2 Original Tier Collection for drop 7, reserved for holders and new community members via whitelist. This ORIGINAL TIER NFT is one of a total supply of 1490 2D X Walker Original Tier NFTs. Original tier NFTs are worth 2 points on our rich list system."",""external_url"":""https://xrpwalkers.com/"",""attributes"":[],""category"":""art"",""md5hash"":""f27b5eafb8d66c431a3aaa8d38c727b2"",""is_explicit"":false,""content_type"":""image/png"",""image_url"":""ipfs://ipfs/bafybeiggmne3egr423wzknxldnjtzvn5u5gxp7hcsiumlouvnztc5ffcru/image.jpeg"",""animation_url"":""ipfs://ipfs/bafybeiggmne3egr423wzknxldnjtzvn5u5gxp7hcsiumlouvnztc5ffcru/animation.png""}")]
        
        [TestCase("dApp Walker", "ipfs://bafybeiga52c65sw2jj6w6jyb3p5pjhzciwphuswf2dqfdjpl36dezmi4om/288.png", @"{ ""schema"": ""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"", ""nftType"": ""art.v0"", ""name"": ""dApp Walker #288"", ""description"": ""The next phase of xToadz NFTs! 1200 walking friends, fully animated, with custom backgrounds, music, and over 160 traits. Holders recieve a 1 million RIBBITS airdrop 48 hours after mint out + exclusive features on the upcoming xToadz dApp."", ""video"": ""ipfs://bafybeidfpie3swy53twuhzcmqe5s5oq2neqy2uq36hbcto6nypxkv3rwgy/288.mp4"", ""image"": ""ipfs://bafybeiga52c65sw2jj6w6jyb3p5pjhzciwphuswf2dqfdjpl36dezmi4om/288.png"", ""collection"": { ""name"": ""dApp Walkers"", ""family"": ""Toadz"", ""image"": ""ipfs://bafybeib7o5z3bjalerym7nrplfbkbly3rnguhpcb3mwhg6fe2zfojadrxm"" }, ""attributes"": [ { ""trait_type"": ""Background"", ""description"": ""Static perfection."", ""value"": ""Noise"" }, { ""trait_type"": ""Skin"", ""description"": ""Reduce palette, minimalism, cartoonish perfecttion."", ""value"": ""Cartoon"" }, { ""trait_type"": ""Chest"", ""description"": ""A wonderful blouse for a special someone like yourself."", ""value"": ""Blouse"" }, { ""trait_type"": ""Face"", ""description"": ""Big, beautiful eyes full of love."", ""value"": ""I Luh You"" }, { ""trait_type"": ""Head"", ""description"": ""Thank you Mother Earth for your bounty and free showers."", ""value"": ""Free Shower"" }, { ""trait_type"": ""Legs"", ""description"": ""These pants are blue. You wear them when you feel jaunty."", ""value"": ""Blue Pants"" }, { ""trait_type"": ""Feet"", ""description"": ""Classic angel style with modern construction. The best of both worlds and currently on your heavenly feet."", ""value"": ""Angel"" }, { ""trait_type"": ""Hand"", ""description"": ""This is your basic hand. Don't worry fren. You may not have a dope-ass revolver, but you can still pick up mail and order sushi."", ""value"": ""Hand"" }, { ""trait_type"": ""Music"", ""description"": ""The Interns Are Flammable, as proven yesterday"", ""value"": ""The Interns Are Flammable, as proven yesterday"" } ] }")]
        
        [TestCase("Coreum Punks", "ipfs://ipfs/bafybeihe3ogoilac3s7yet4lyo6m4wsm5a7ws5sftwztbza5qrv4ilhphu/image.png", @"{""name"":""Coreum Punks #1998"",""description"":""Coreum Punks on the XRPL"",""external_url"":""https://coreumpunks.com/"",""attributes"":[{""trait_type"":""background"",""value"":""core.7""},{""trait_type"":""base"",""value"":""Base.6""},{""trait_type"":""clothing"",""value"":""Hoodie_19""},{""trait_type"":""headtrait"",""value"":""Jester.hat.2""},{""trait_type"":""eyetrait"",""value"":""Core.eye""},{""trait_type"":""mouth"",""value"":""Clear.1""}],""category"":""collectibles"",""md5hash"":""f64afb67c4fd0a54c53b7a9712262ce9"",""is_explicit"":false,""content_type"":""image/png"",""image_url"":""ipfs://ipfs/bafybeihe3ogoilac3s7yet4lyo6m4wsm5a7ws5sftwztbza5qrv4ilhphu/image.png"",""animation_url"":""ipfs://ipfs/bafybeihe3ogoilac3s7yet4lyo6m4wsm5a7ws5sftwztbza5qrv4ilhphu/animation.png""}")]
        
        [TestCase("Power Zerp", "ipfs://bafybeicnjdog2dwizg7iudk3ycsowrxrtukvmf42plorm6gxgwc3gfvboy/2149.png", @"{ ""schema"": ""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"", ""nftType"": ""art.v0"", ""external_url"": ""https://www.powerzerps.com"", ""name"": ""Power Zerp #7013"", ""description"": ""Power Zerp #7013 is part of Power Zerps Collection, created by Ekiserrepe (Ekiserrepe.com)."", ""image"": ""ipfs://bafybeicnjdog2dwizg7iudk3ycsowrxrtukvmf42plorm6gxgwc3gfvboy/2149.png"", ""collection"": { ""name"": ""Power Zerps"", ""family"": ""Power Zerps"" }, ""attributes"": [ { ""trait_type"": ""Helmet"", ""value"": ""Hero"" }, { ""trait_type"": ""Body Armor"", ""value"": ""Thorn"" }, { ""trait_type"": ""Color"", ""value"": ""Grey"" }, { ""trait_type"": ""Attack"", ""value"": ""3"" }, { ""trait_type"": ""Defense"", ""value"": ""5"" }, { ""trait_type"": ""Health"", ""value"": ""1"" }, { ""trait_type"": ""Magic"", ""value"": ""3"" } ] }")]
        
        [TestCase("Baysed Birds Trading Cards", "ipfs://bafybeie5qmrz64pdzr7vqr6uk66nwnxknntun3iexcjcqrxxbcm2nakl5m/orange.png", @"{ ""name"": ""Orange"", ""image"": ""ipfs://bafybeie5qmrz64pdzr7vqr6uk66nwnxknntun3iexcjcqrxxbcm2nakl5m/orange.png"", ""collection"": { ""name"": ""Baysed Birds Trading Cards"", ""description"": ""Official trading cards of baysed birds! By Baysed Labs!"", ""image"": ""ipfs://bafybeidhdscjvivy7tj2fbb6clrpdc6qdi5uiwlujigo5egrd3p2ewepiu/Baysed_labs-fin-01.png"" }, ""attributes"": [ { ""trait_type"": ""Trait"", ""value"": ""Body"" }, { ""trait_type"": ""Rarity"", ""value"": ""Common"" } ] }")]

        [TestCase("The Third Gen2 Original Tier Collection", "ipfs://ipfs/bafybeic3avqnofz2apjl53ndg3vs7iyttfvp7xn4ojb62dus5cmy4wjplm/image.jpeg", @"{""name"":""XWX 0269"",""description"":""This NFT was sold as part of The Third Gen2 Original Tier Collection for drop 8, reserved for holders and new community members via whitelist. This ORIGINAL TIER NFT is one of a total supply of 1490 2D X Walker Original Tier NFTs. Original tier NFTs are worth 2 points on our rich list system."",""external_url"":""https://xrpwalkers.com/"",""attributes"":[],""category"":""art"",""md5hash"":""84b040ef3620b340d2bb1e572fd28b01"",""is_explicit"":false,""content_type"":""image/png"",""image_url"":""ipfs://ipfs/bafybeic3avqnofz2apjl53ndg3vs7iyttfvp7xn4ojb62dus5cmy4wjplm/image.jpeg"",""animation_url"":""ipfs://ipfs/bafybeic3avqnofz2apjl53ndg3vs7iyttfvp7xn4ojb62dus5cmy4wjplm/animation.png""}")]

        [TestCase("REAPER GENESIS COLLECTION", "ipfs://ipfs/bafybeif3yots6lz6he7u2xoqapwok3k3tilr4gmsdruqhjobwhqjoi2hhq/image.jpeg", @"{""name"":""Genesis 20"",""category"":""collectibles"",""md5hash"":""6e3d5bf9f77895ba776e65fe9f3d3488"",""content_type"":""image/jpeg"",""description"":""This card is a part of the first NFT collection for @TheReaperCoin ($RPR). \n\nRepresenting TheReaper at it&#x27;s various tasks, these NFTs bring the value of Death to Life.\n\nDYOR TheReaperCoin at: http:&#x2F;&#x2F;thereaper.io\nJoin Telegram at: http:&#x2F;&#x2F;t.me&#x2F;thereaperofficial\n\nNFT artwork done by Sumi Stik &#x2F; xSTIK Official:\nhttp:&#x2F;&#x2F;xrpstik.com&#x2F;nft-workshop&#x2F;"",""is_explicit"":false,""external_url"":""https://TheReaper.io"",""animation_url"":""ipfs://ipfs/bafybeieh4dyw5gul4rjqvsydhxtc7odgckmxkxvuytxymgnlxtlqvfqpim/data.jpeg"",""attributes"":[{""trait_type"":""vip_access"",""value"":""Reaper Conventions""},{""trait_type"":""reaper_genesis_collection"",""value"":20,""max_value"":100},{""trait_type"":""first_collection"",""value"":1,""max_value"":1}],""image_url"":""ipfs://ipfs/bafybeif3yots6lz6he7u2xoqapwok3k3tilr4gmsdruqhjobwhqjoi2hhq/image.jpeg""}")]
        
        [TestCase("Doodle Moonbois", "ipfs://bafybeibpmbtwz7g4tuz6mfj7whmgqj2lsx3cshdzhregz73wx5kixzlpfe/818.png", @"{ ""name"": ""Doodle Moonboi #818"", ""image"": ""ipfs://bafybeibpmbtwz7g4tuz6mfj7whmgqj2lsx3cshdzhregz73wx5kixzlpfe/818.png"", ""collection"": { ""name"": ""Doodle Moonbois"", ""description"": ""Doodle Moonbois - a collection of 1000 NFT digital arts living on XRPL. We believe that every Moonboi and Moongirl deserves to have their own PFP."", ""image"": ""ipfs://bafybeih5uvfqy32ql6rmidcco3ku53256e3e7trelw6upx5fphmsluiakq/94.png"" }, ""attributes"": [ { ""trait_type"": ""Background"", ""value"": ""Dawn Pink"" }, { ""trait_type"": ""Body"", ""value"": ""Yellow Suit"" }, { ""trait_type"": ""Helmet"", ""value"": ""Green"" }, { ""trait_type"": ""Glass"", ""value"": ""Cold Purple"" } ] }")]
        
        [TestCase("Pixel Astros", "ipfs://bafybeidatlx2zmawrulygptxpjbpbmvxut4t2w4qryguysb4njluovtmti/1681933818964.png", @"{""attributes"":[{""description"":""Background"",""trait_type"":""Background"",""value"":""Yellow""},{""description"":""Body"",""trait_type"":""Body"",""value"":""RoseGoldChain""},{""description"":""Helmet"",""trait_type"":""Helmet"",""value"":""ColourBarsPatch""},{""description"":""Mouth"",""trait_type"":""Mouth"",""value"":""Blank""},{""description"":""Headware"",""trait_type"":""Headware"",""value"":""Blank""},{""description"":""Badge"",""trait_type"":""Badge"",""value"":""Silver""}],""collection"":{""name"":""Pixel Astros"",""family"":""Pixel Astros""},""video"":"""",""animation"":"""",""external_link"":"""",""audio"":"""",""name"":""Pixel Astros #287"",""image"":""ipfs://bafybeidatlx2zmawrulygptxpjbpbmvxut4t2w4qryguysb4njluovtmti/1681933818964.png"",""taxon"":34637,""description"":""A collection of 5000 Pixel Astros have been created to celebrate the AstroNaughties first birthday. The AstroNaughties are a bunch of rebellious, rascal astronauts heading to the Moon! Owning an AstroNaughtie grants you access and membership to the exclusive Moon Polo Club. Benefits include access to IRL events, Astro merch and AstroNaughtie rewards."",""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""id"":""0ead3611bc89af6d9eac0fe5a240c82f:1681933818943"",""file"":""""}")]
        
        [TestCase("XRPL Moonbirds", "ipfs://bafybeidata3w2tvryxxcyprazhgh6ggt4o5lbrtxwabw3aun2lkkzcupie/1681232347506.png", @"{""attributes"":[{""description"":""Specie"",""trait_type"":""Specie"",""value"":""Owl""},{""description"":""Eyes"",""trait_type"":""Eyes"",""value"":""Angry - Blue""},{""description"":""Headwear"",""trait_type"":""Headwear"",""value"":""Fire""},{""description"":""Body"",""trait_type"":""Body"",""value"":""Stark""},{""description"":""Feathers"",""trait_type"":""Feathers"",""value"":""Brown""},{""description"":""Background"",""trait_type"":""Background"",""value"":""XRPL Moon Blue""},{""description"":""Beak"",""trait_type"":""Beak"",""value"":""Short - Orange""}],""collection"":{""name"":""XRPL Moonbirds"",""family"":""XRPL Moonbirds""},""video"":"""",""animation"":"""",""external_link"":"""",""audio"":"""",""name"":""XRPL Moonbirds #9572"",""image"":""ipfs://bafybeidata3w2tvryxxcyprazhgh6ggt4o5lbrtxwabw3aun2lkkzcupie/1681232347506.png"",""taxon"":31063,""description"":""10000 Digital XRPL Moonbirds"",""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""id"":""6c90e0229b087b273ff7358a8d3dca06:1681232347473"",""file"":""""}")]
        
        [TestCase("Zen Lounge", "ipfs://ipfs/bafybeidrc2whxno4syezji4oggoohoowjrxq5fieasrahtcxsw5uxfytcu/image.jpeg", @"{""name"":""Zen Lounge Glock"",""description"":""Zen Lounge Glock 9mm.\n\nArt by Dorian White - @esotericvisionaryart"",""external_url"":""https://linktr.ee/esoteric.visions"",""attributes"":[{""trait_type"":""zen_lounge_glock"",""value"":0,""max_value"":7}],""category"":""collectibles"",""md5hash"":""2753aa754909fd662a8abf21633e4c9f"",""is_explicit"":false,""content_type"":""image/png"",""image_url"":""ipfs://ipfs/bafybeidrc2whxno4syezji4oggoohoowjrxq5fieasrahtcxsw5uxfytcu/image.jpeg"",""animation_url"":""ipfs://ipfs/bafybeidrc2whxno4syezji4oggoohoowjrxq5fieasrahtcxsw5uxfytcu/animation.png""}")]
        
        [TestCase("X-Saberz", "ipfs://ipfs/bafybeifkgwkflernfoi4xnm4vpnexvgvbytdogzteaujljqb6whbo2wdl4/image.jpeg", @"{""name"":""X-SBR #095"",""description"":""Part of the Genesis Collection. 100 fully built X-Saberz."",""external_url"":"""",""attributes"":[{""trait_type"":""faction"",""value"":""Street""},{""trait_type"":""attack_high"",""value"":""1515""},{""trait_type"":""attack_low"",""value"":""1000""},{""trait_type"":""defense_high"",""value"":""2045""},{""trait_type"":""defense_low"",""value"":""1500""},{""trait_type"":""rarity"",""value"":""Legendary""}],""category"":""collectibles"",""md5hash"":""7b3963da431f8ebd3a30abc2b62e87b4"",""is_explicit"":false,""content_type"":""image/png"",""image_url"":""ipfs://ipfs/bafybeifkgwkflernfoi4xnm4vpnexvgvbytdogzteaujljqb6whbo2wdl4/image.jpeg"",""animation_url"":""ipfs://ipfs/bafybeifkgwkflernfoi4xnm4vpnexvgvbytdogzteaujljqb6whbo2wdl4/animation.png""}")]
        
        [TestCase("xrpwalkers", "ipfs://ipfs/bafybeiagngkxslwg2igpgio74hper3wfreoqreh3ksgd6slanmbkmefuwa/image.jpeg", @"{""name"":""XWX 0358"",""description"":""This NFT was sold as part of The Fourth Gen2 Original Tier Collection for drop 9, Christmas themed and reserved for holders and new community members via whitelist. This ORIGINAL TIER NFT is one of a total supply of 1490 2D X Walker Original Tier NFTs. Original tier NFTs are worth 2 points on our rich list system."",""external_url"":""https://xrpwalkers.com/"",""attributes"":[],""category"":""art"",""md5hash"":""25389785dd79ca4fa26855d85a59896d"",""is_explicit"":false,""content_type"":""image/png"",""image_url"":""ipfs://ipfs/bafybeiagngkxslwg2igpgio74hper3wfreoqreh3ksgd6slanmbkmefuwa/image.jpeg"",""animation_url"":""ipfs://ipfs/bafybeiagngkxslwg2igpgio74hper3wfreoqreh3ksgd6slanmbkmefuwa/animation.png""}")]
        
        [TestCase("BOT PUNK", "ipfs://bafybeiek4j6yn3p3jvoxxsmfttzprfn7en3togmslm6yjloolajcoqpzju/6027.png", @"{ ""name"": ""BOT PUNK #6027"", ""image"": ""ipfs://bafybeiek4j6yn3p3jvoxxsmfttzprfn7en3togmslm6yjloolajcoqpzju/6027.png"", ""collection"": { ""name"": ""BOT PUNKS"", ""description"": ""10,000 Pixelated BOT PUNKS brought to you by XBOT CLUB!"", ""image"": ""ipfs://bafybeign3r5vp3gdli4gbn3hwrohr2bmdzft3myz6cdapib4gqmx3i5vau/0.png"" }, ""attributes"": [ { ""trait_type"": ""Display"", ""value"": ""Purple"" }, { ""trait_type"": ""Jaw"", ""value"": ""None"" }, { ""trait_type"": ""Head"", ""value"": ""Knight"" }, { ""trait_type"": ""Neck"", ""value"": ""None"" }, { ""trait_type"": ""Plating"", ""value"": ""Red"" }, { ""trait_type"": ""Background"", ""value"": ""Purple"" } ] }")]
        
        [TestCase("Unchained Elephants", "ipfs://bafybeihy5vswmsumw42g367e45o2hqux6ab2j7mnb4qw64fecw5dxxaqwe", @"{ ""schema"": ""ipfs://bafkreidtjf2ihiwtptiyadjfmesplo555iy2jdcwhfr6hkenr2z3fvxn2y"", ""nftType"": ""art.v0"", ""name"": ""Unchained Elephant #87"", ""description"": ""Unchained Elephants NFT is a collection of 9,999 digital artworks on the XRPL featuring stunning visuals of elephants. Crafted to raise awareness and support the rescue of working elephants in Thailand while also building an exclusive community of passionate travelers. The Original Herd NFT is the exclusive collection of 99 hand-drawn digital artworks forming the foundation of the larger Unchained Elephants collection. These original artworks were meticulously crafted by the talented Ecuadorian artist, \""Huesos Negros\"". Each piece showcases an elephant in a serene state of meditation surrounded by a diverse array of backgrounds and props. Join us in celebrating the majestic nature of these incredible creatures and immerse yourself in the tranquility and beauty of the Original Herd. Explore more at www.unchainedelephants.com"", ""image"": ""ipfs://bafybeihy5vswmsumw42g367e45o2hqux6ab2j7mnb4qw64fecw5dxxaqwe"", ""animation"": """", ""video"": """", ""audio"": """", ""3d_model"": """", ""collection"": { ""name"": ""Unchained Elephants"" }, ""attributes"": [ { ""trait_type"": ""Collection"", ""value"": ""Original Herd"" }, { ""trait_type"": ""Head"", ""value"": ""Long Black Hair"" }, { ""trait_type"": ""Background"", ""value"": ""Violet Blaze"" }, { ""trait_type"": ""Outfit"", ""value"": ""Tiger Tattoo"" }, { ""trait_type"": ""Skin"", ""value"": ""White Elephant"" }, { ""trait_type"": ""Accessory"", ""value"": ""Leo Zodiac Sign"" } ], ""license"": ""None"" }")]
        
        [TestCase("X Walkers 3D", "ipfs://ipfs/bafybeiasdukjhf7pugvdv2ky76zcnjf7mufcydehktmxgr5hfw2v6mgja4/image.jpeg", @"{""name"":""XW3D 052"",""description"":""This is 1 of 100 X Walkers 3D NFTs. 3D NFTs are worth 5 points on the X Walkers richlist."",""external_url"":""https://xrpwalkers.com/"",""attributes"":[],""category"":""art"",""md5hash"":""6a75611229e1197bd7f0b6795afebff4"",""is_explicit"":false,""content_type"":""image/png"",""image_url"":""ipfs://ipfs/bafybeiasdukjhf7pugvdv2ky76zcnjf7mufcydehktmxgr5hfw2v6mgja4/image.jpeg"",""animation_url"":""ipfs://ipfs/bafybeiasdukjhf7pugvdv2ky76zcnjf7mufcydehktmxgr5hfw2v6mgja4/animation.png""}")]
        
        [TestCase("XFLOKI GEN 1", "ipfs://QmTSGyTAj1DHh2ts9S7pqm7X76d6oZqF4FpPq74ru7trZQ", @"{ ""name"": ""XFLOKI GENERATION 1 #010687"", ""description"": ""A finely minted XFLOKI from our very own XFLOKIGEN on the XRP ledger! This is a first generation XFLOKI! #010687"", ""image"": ""ipfs://QmTSGyTAj1DHh2ts9S7pqm7X76d6oZqF4FpPq74ru7trZQ"", ""external_url"": ""https://xflokiverse.com/"", ""attributes"": [ { ""trait_type"": ""Background"", ""value"": ""Circus"" }, { ""trait_type"": ""Body"", ""value"": ""XFLOKI Body"" }, { ""trait_type"": ""Head"", ""value"": ""Pixel No Face XFLOKI Green"" }, { ""trait_type"": ""Facial Expression"", ""value"": ""Sleeping"" }, { ""trait_type"": ""Face Accessory"", ""value"": ""Heart Glasses"" }, { ""trait_type"": ""HP"", ""value"": ""5079"" }, { ""trait_type"": ""Defense"", ""value"": ""1"" }, { ""trait_type"": ""Power"", ""value"": ""3552"" }, { ""trait_type"": ""Elemental"", ""value"": ""Fire"" } ], ""collection"": [ { ""family"": ""XFLOKI"", ""name"": ""XFLOKI GEN 1"" } ], ""edition"": ""1"", ""date"": ""1663088889000"", ""compiler"": ""XFLOKIVERSE"" }")]

        [TestCase("Pearlescent", "ipfs://QmSu8DCLvMhFF8WdwpStsDc9VutzYpkSCVHkWbcfdPLjkJ/471.png", @"{ ""name"": ""XBLADE #471"", ""description"": ""Xblades are a collection of 8,888 unique powerful blades. Unique digital collectibles living on the XRPL. Your Xblade is your premium NFT that grants access to a number of things, such as XscapeNFT and StaykX utility, priority access to future XscapeNFT collections, and future airdrops. Visit xscapenft.com for more details."", ""image"": ""ipfs://QmSu8DCLvMhFF8WdwpStsDc9VutzYpkSCVHkWbcfdPLjkJ/471.png"", ""attributes"": [ { ""trait_type"": ""Effect"", ""value"": ""Smokey - Amethyst_Pearl"" }, { ""trait_type"": ""Blade"", ""value"": ""Jungle Blade - Emerald_Pearl"" }, { ""trait_type"": ""Hilt"", ""value"": ""Yue Hilt - Amethyst_Pearl"" }, { ""trait_type"": ""Handle"", ""value"": ""Space Handle - Ruby_Pearl"" }, { ""trait_type"": ""Glow"", ""value"": ""Holy Fire"" }, { ""trait_type"": ""Background"", ""value"": ""Facility - Sapphire_Pearl"" } ], ""collection"": { ""family"": ""Xblades"", ""name"": ""Pearlescent"" }, ""edition"": 1 }")]

        [TestCase("xDUDEz", "ipfs://bafybeib4jeet36lqzabt2ebqgak4fdkms2p5w6jf5j2dtoyfvmyamtcn2y/1667249944298.png", @"{""attributes"":[{""description"":""Background"",""trait_type"":""Background"",""value"":""Manhattan bridge at Dusk""},{""description"":""Body"",""trait_type"":""Body"",""value"":""Light tan skin""},{""description"":""Clothes"",""trait_type"":""Clothes"",""value"":""Grey roundneck _ Planet logo""},{""description"":""Eyes"",""trait_type"":""Eyes"",""value"":""Emerald green eyes""},{""description"":""Earrings"",""trait_type"":""Earrings"",""value"":""Gold Earring""},{""description"":""Extra"",""trait_type"":""Extra"",""value"":""Wireless Headphones""}],""collection"":{""name"":""XDUDEZ 2.5K"",""family"":""XDUDEZ""},""video"":"""",""animation"":"""",""external_link"":"""",""audio"":"""",""name"":""#1351"",""image"":""ipfs://bafybeib4jeet36lqzabt2ebqgak4fdkms2p5w6jf5j2dtoyfvmyamtcn2y/1667249944298.png"",""taxon"":63,""description"":""xDUDEz 2.5K"",""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""id"":""de6824b9fcb8286d0425564ea2eda0be:1667249944290"",""file"":""""}")]

        [TestCase("PunkWorlds", "ipfs://bafybeibzzvxznatzefhl37susdaigs7weay6oqkscryxycu64fzpkhgr4m/7470.jpg", @"{ ""schema"": ""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"", ""nftType"": ""art.v0"", ""name"": ""PunkWorlds #7470"", ""description"": ""PunkWorlds are generated using AI and neural programming to meticulously create an original scene rendered in high quality. Holding Punkworld collectible allows access to other AI creations and bonus collectibles."", ""image"": ""ipfs://bafybeibzzvxznatzefhl37susdaigs7weay6oqkscryxycu64fzpkhgr4m/7470.jpg"", ""image_url"": ""ipfs://bafybeibzzvxznatzefhl37susdaigs7weay6oqkscryxycu64fzpkhgr4m/7470.jpg"", ""category"": ""art"", ""content_type"": ""image/jpeg"", ""collection"": { ""family"": ""PunkWorlds"", ""name"": ""PunkWorlds"" }, ""attributes"": [ { ""trait_type"": ""Type"", ""value"": ""Male"" }, { ""trait_type"": ""Accessory"", ""value"": ""Vampire Hair"" }, { ""trait_type"": ""Accessory"", ""value"": ""Earring"" }, { ""trait_type"": ""Accessory"", ""value"": ""Clown Eyes Green"" }, { ""trait_type"": ""Attributes Count"", ""value"": 3 }, { ""trait_type"": ""Spirit"", ""value"": ""Utopian City"" } ], ""external_url"": ""https://punkworlds.art"", ""edition"": 7470, ""date"": 1668124800000, ""compiler"": ""PunkWorlds Team"" }")]

        [TestCase("Assigens", "ipfs://bafybeifscwg6yh7mu2vfwmputyiiab7llt2q3763zrbrcewj6b5v5vr3te", @"{""schema"":""https://www.nftmaster.com/metadata"",""nftType"":""nftmaster.v0"",""name"":""Assigens #1789"",""category"":""collectibles"",""description"":""\u0022Satoshi is not one, but many\u0022 - These collectibles were inspired by a complex and compelling universe about technology, society and futurism.The story is aimed to give a literacy background to some \u220E\u026F\u0250\u01DD\u0279\u0287su\u0131\u0250\u20A5\u029E\u0254n\u025F NFT collections and produce an entertainment driven utility. Assigens are also the key to breed something when combined hodling with \u0022Assimovs\u0022 is pushed into the \u20A5 Server. This collection is part of the \u2396unflake 2022 series, the early NFTs of the \u20A5 tribe. The minters of these pieces are the first wave. Each Assigen represents the laboratory testimony of \u20A5 scientists trying to create the perfect human being with cryptographic genes, better known as \u20A5 blocks. These were created at the end of the Satoshi\u00B4s era when humans began encrypting genetic material into the quantum chain."",""image"":""ipfs://bafybeifscwg6yh7mu2vfwmputyiiab7llt2q3763zrbrcewj6b5v5vr3te"",""video"":null,""animation"":null,""audio"":null,""file"":null,""external_link"":""https://unflake.wtf/"",""location"":null,""collection"":{""name"":""Assigens"",""family"":""\u0022Satoshi is not one, but many\u0022 - These collectibles were inspired by a complex and compelling universe about technology, society and futurism.The story is aimed to give a literacy background to some \u220E\u026F\u0250\u01DD\u0279\u0287su\u0131\u0250\u20A5\u029E\u0254n\u025F NFT collections and produce an entertainment driven utility. Assigens are also the key to breed something when combined hodling with \u0022Assimovs\u0022 is pushed into the \u20A5 Server. This collection is part of the \u2396unflake 2022 series, the early NFTs of the \u20A5 tribe. The minters of these pieces are the first wave. Each Assigen represents the laboratory testimony of \u20A5 scientists trying to create the perfect human being with cryptographic genes, better known as \u20A5 blocks. These were created at the end of the Satoshi\u00B4s era when humans began encrypting genetic material into the quantum chain.""},""attributes"":[{""name"":""CONSOLE_FRAMEWORK"",""value"":""WHITE FK\u20A5 TAPES""},{""name"":""WRAP_TYPE"",""value"":""MEDICAL PRODUCTS""},{""name"":""SKIN_COLOR"",""value"":""ORGANIC MARBLE""},{""name"":""CELL_STRUCTURE"",""value"":""KERATIN""},{""name"":""TAPE_TYPE"",""value"":""ROTTEN MASKIN""},{""name"":""SNIPPET"",""value"":""satoshi is gov""},{""name"":""LAB_ID"",""value"":""WASHINGTON""},{""name"":""DEAD_REASON"",""value"":""Not Enough Data""},{""name"":""HUMANITY_TYPE"",""value"":""Cyborg""}]}")]

        [TestCase("Lux Lions", "ipfs://bafybeiem6dtk4hny3flkhvt4a2ixviwnom53kesixdsgo7hpsn52fkbtbm/1679413792105.png", @"{""attributes"":[],""collection"":{""name"":""Lux Lions Hunter & Huntress"",""family"":""Lux Lions""},""video"":"""",""animation"":"""",""external_link"":"""",""audio"":"""",""name"":""Lux Lions Hunter 5 "",""image"":""ipfs://bafybeiem6dtk4hny3flkhvt4a2ixviwnom53kesixdsgo7hpsn52fkbtbm/1679413792105.png"",""taxon"":10745,""description"":"""",""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""id"":""d1f606c1-89a8-5652-f56d-0185d000b007:1679413795545"",""file"":""""}")]

        [TestCase("Legends", "ipfs://bafybeidq4bjsc5vskem5nvllr3m3wtwpglicfuv5eddifkhbbpshh3oqm4/469.png", @"{ ""name"": ""Dark Prince #44"", ""image"": ""ipfs://bafybeidq4bjsc5vskem5nvllr3m3wtwpglicfuv5eddifkhbbpshh3oqm4/469.png"", ""collection"": { ""name"": ""Legends"", ""description"": ""The Xscape Legends NFT collection is a limited supply, celebration of the XscapeNFT community. As a token of our appreciation to the core community, we created a variety of completely unique characters and cemented them into our universe, based on those various community members in real life. Visit xscapenft.com for more details."", ""image"": ""ipfs://bafybeif6hm55qs44nlbjso2eh3jc246terycbb4ykzfxhsk5lztxekk4di"" }, ""alternative_sources"": { ""image"": [ ""https://arweave.net/ieq1v6U2zGuQXT5aYJVdVbwKVrJNrDBU-zEC-IFKR64/469.png"" ], ""collection"": { ""image"": [ ""https://arweave.net/cWrmb8Bd9VJ-MBpi44Y0w_IOk0aoSjFRnWs5UMEoLKM"" ] } }, ""attributes"": [ { ""trait_type"": ""Legend"", ""value"": ""Dark Prince"" }, { ""trait_type"": ""Signature"", ""value"": ""Madfly"" }, { ""trait_type"": ""Border"", ""value"": ""Demonic"" }, { ""trait_type"": ""Effect"", ""value"": ""Bubbles - Gold"" } ] }")]

        [TestCase("PNKs.", "https://arweave.net/sg95PJOkw_rqhf00hgBmD_AcnB2ndhOIzZ_uPUk-Mgg/PNKs._1609.png", @"{ ""name"": ""PNKs. 1609"", ""image"": ""https://arweave.net/sg95PJOkw_rqhf00hgBmD_AcnB2ndhOIzZ_uPUk-Mgg/PNKs._1609.png"", ""collection"": { ""name"": ""PNKs."", ""description"": ""5890 High-Res 3D Punks."", ""image"": ""https://arweave.net/oxkJ4b1CuSEGuDaqzEIbFk59AHNjKBgafSuTdqpuiTQ"" }, ""attributes"": [ { ""trait_type"": ""Ears"", ""value"": ""No Attribute"" }, { ""trait_type"": ""Eyes"", ""value"": ""Tech Glasses"" }, { ""trait_type"": ""Face"", ""value"": ""No Attribute"" }, { ""trait_type"": ""Head"", ""value"": ""Gray Beanie"" }, { ""trait_type"": ""Mouth"", ""value"": ""Candy Stick"" }, { ""trait_type"": ""Neck"", ""value"": ""Black XRP Chain"" }, { ""trait_type"": ""Type"", ""value"": ""Male 1"" } ] }")]

        //[TestCase("", "", @"")]
        public async Task Given_50To_99NFT_ReturnsImageAsync(
            string projectName,
            string image,
            string metaJson)
        {
            // Arrange
            // Not testing link to metadata for these, so set to anything
            // and return mock meta json anyway
            Token.URI = TestConstants.MetaNormalisedIpfsUrl;
            _mockHttpFacade.GetData(TestConstants.MetaNormalisedIpfsUrl).Returns(metaJson);

            // Act
            var result = await _classUnderTest.ProcessNFToken(Token);

            // Assert
            Assert.That(result, Is.EqualTo(image), message: projectName);
        }
    }
}