using NSubstitute;

namespace UniversalNFT.dev.API.Tests.Services.Rules
{
    public class _150To_200Tests : BaseRuleTest
    {
        [TestCase("Lux Lions OG ", "https://bafybeibchndwcctjmado7rllzv6w6w4whukpv45rzzw56zraa5iuzmg5dm.ipfs.w3s.link/1667187076137.png", @"{""attributes"":[{""description"":""Background"",""trait_type"":""Background"",""value"":""pale Aqua""},{""description"":""Mane Beard"",""trait_type"":""Mane Beard"",""value"":""white""},{""description"":""Skin"",""trait_type"":""Skin"",""value"":""brown""},{""description"":""Clothing"",""trait_type"":""Clothing"",""value"":""chef Uniform""},{""description"":""Mouth"",""trait_type"":""Mouth"",""value"":""smile""},{""description"":""Eyes"",""trait_type"":""Eyes"",""value"":""sunglasses""},{""description"":""Headgear"",""trait_type"":""Headgear"",""value"":""santa Hat""}],""collection"":{""name"":""Lux Lions OG (XLUX)"",""family"":""Lux Lions""},""video"":"""",""animation"":"""",""external_link"":"""",""audio"":"""",""name"":""Lux Lions #4360"",""image"":""https://bafybeibchndwcctjmado7rllzv6w6w4whukpv45rzzw56zraa5iuzmg5dm.ipfs.w3s.link/1667187076137.png"",""taxon"":38,""description"":""The Lux Lions are the future of the XRP Ledger. Join us as we take over the world lion by lion and pride by pride."",""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""id"":""b8ef2b70d1cab480d811b476ece4a348:1667187076122"",""file"":""""}")]

        [TestCase("XMEME COLLECTION", "ipfs://bafkreihiicuhwqots7tjd6k3jhofth7dkrcdb2tfmsixg3ybmbumal5hqi", @"{ ""schema"": ""ipfs://bafkreidtjf2ihiwtptiyadjfmesplo555iy2jdcwhfr6hkenr2z3fvxn2y"", ""nftType"": ""art.v0"", ""name"": ""XMEME MASTERPIECE #4"", ""description"": ""Only 50 XMEME exclusive masterpieces will ever exist"", ""image"": ""ipfs://bafkreihiicuhwqots7tjd6k3jhofth7dkrcdb2tfmsixg3ybmbumal5hqi"", ""animation"": """", ""video"": """", ""audio"": """", ""3d_model"": """", ""collection"": { ""name"": ""XMEME COLLECTION #2"" }, ""attributes"": [], ""license"": ""None"" }")]

        [TestCase("XparrotsNFT", "ipfs://bafybeieyz6pweriovxesgg4r5fcwp44go63au3w5nunfz4mznymsmec43m/1667237693761.png", @"{""attributes"":[{""description"":""Background"",""trait_type"":""Background"",""value"":""BG10""},{""description"":""Parrots"",""trait_type"":""Parrots"",""value"":""PARROT (LIGHT-GREEN)""},{""description"":""clothes"",""trait_type"":""clothes"",""value"":""HOODED3""},{""description"":""eyes"",""trait_type"":""eyes"",""value"":""angry eye""},{""description"":""Glasses"",""trait_type"":""Glasses"",""value"":""Sun shades""}],""collection"":{""name"":""XparrotsNFT"",""family"":""XparrotsNFT""},""video"":"""",""animation"":"""",""external_link"":"""",""audio"":"""",""name"":""#1592"",""image"":""ipfs://bafybeieyz6pweriovxesgg4r5fcwp44go63au3w5nunfz4mznymsmec43m/1667237693761.png"",""taxon"":49,""description"":"""",""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""id"":""d71ab8d90edbbec678967e3833a8d889:1667237693751"",""file"":""""}")]

        [TestCase("X-Avatars", "ipfs://QmSoChfDt1ZZJq6gnoraGRhH6gVMLSaeUqDewdXGafp9wP", @"{ ""schema"": ""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"", ""name"": ""The Final Countdown #12"", ""description"": ""One. Two. Three. Hold tight your xrp."", ""nftType"": ""art.v0"", ""collection"": { ""name"": ""X-Avatars"" }, ""attributes"": [], ""image"": ""ipfs://QmSoChfDt1ZZJq6gnoraGRhH6gVMLSaeUqDewdXGafp9wP"", ""video"": ""ipfs://QmWBtGyaBEPtqeC8FVT3cE5pJmQmcMowNTR7AvkrqJ9Zpp"", ""additional_properties"": { ""author"": { ""type"": ""default"", ""version"": ""1.0.0"", ""name"": ""X-Art"" }, ""type"": ""Aesthetes-XLS24"", ""version"": ""1.0.0"", ""content"": ""cid:QmWBtGyaBEPtqeC8FVT3cE5pJmQmcMowNTR7AvkrqJ9Zpp"" } }")]

        [TestCase("Terror Teddies Genesis", "ipfs://bafybeihuftlcerusjax6zbswoyadkqsd5f5wyz66kwlqqs3a6277ywqxqe/1688070855142.png", @"{""attributes"":[{""description"":""Background"",""trait_type"":""Background"",""value"":""Catacombs""},{""description"":""Body"",""trait_type"":""Body"",""value"":""green""},{""description"":""Clothes"",""trait_type"":""Clothes"",""value"":""Hawaiian""},{""description"":""Hand"",""trait_type"":""Hand"",""value"":""Microphone""},{""description"":""Mouth"",""trait_type"":""Mouth"",""value"":""Hillbilly""},{""description"":""Eyes"",""trait_type"":""Eyes"",""value"":""DvsBans""},{""description"":""Head"",""trait_type"":""Head"",""value"":""Native""},{""description"":""NFT License"",""trait_type"":""NFT License"",""value"":""CID Reference bafybeibj32ggfmlo42vzy6rkdtgz7hvshjrrs5knorbgjmb3t72a7efkxu""}],""collection"":{""name"":""Terror Teddies Genesis"",""family"":""Terror Teddies Genesis""},""video"":"""",""animation"":"""",""external_link"":"""",""audio"":"""",""name"":""Terror Teddies Genesis Collection #3999"",""image"":""ipfs://bafybeihuftlcerusjax6zbswoyadkqsd5f5wyz66kwlqqs3a6277ywqxqe/1688070855142.png"",""taxon"":46569,""description"":""3,999 mutated teddies to terrorize the XRP Ledger. Artwork includes NFT License (https://nftstorage.link/ipfs/bafybeibj32ggfmlo42vzy6rkdtgz7hvshjrrs5knorbgjmb3t72a7efkxu) and Terror Teddies all access membership pass. https://terrorteddies.com"",""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""id"":""589db9ecf72fe950dfe0d325f102dc48:1688070855124"",""file"":""""}")]

        [TestCase("Sunrise Armor ", "ipfs://bafybeigoxi6zqmo2bejisqubuouzl2qmomkwamjhfler4wv2wip3k3efmq", @"{""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""name"":""Sunrise Armor (Legendary)"",""description"":""The Full Sunrise Armor Legendary version is a cosmetic set consisting of 5 individual pieces Body Armor, Helmet, Pants, Boots and Gloves"",""additional"":""Cosmetic Armor Skin usable in all games developed by Equilibrium Games and many partnered games"",""network"":""XLS20 Mainnet"",""attributes"":[{""trait_type"":""rarity"",""value"":""legendary""},{""trait_type"":""Type"",""value"":""Cosmetic""},{""trait_type"":""Set"",""value"":""Full""}],""image"":""ipfs://bafybeigoxi6zqmo2bejisqubuouzl2qmomkwamjhfler4wv2wip3k3efmq"",""collection"":{""name"":""Sunrise Armor (Legendary)"",""family"":""Blights Wrath""}}")]

        [TestCase("Critters & Crawlers", "ipfs://QmVsUyzE2nangekhEdhpNWBWje325mSaNetAk5cXkhbCvJ", @"{ ""name"": ""Drowsy Droid #3658"", ""description"": ""The Drowsy Droids are a diverse and versatile line of personal assistant robots designed to meet the needs of the various residents in the Undercity. Equipped with advanced artificial intelligence and a range of other helpful features, these droids can handle a wide range of requests and demands."", ""collection"": ""Critters & Crawlers"", ""edition"": 1, ""custom_id"": ""020009003014005018009014"", ""image"": ""ipfs://QmVsUyzE2nangekhEdhpNWBWje325mSaNetAk5cXkhbCvJ"", ""attributes"": [ { ""trait_type"": ""Head"", ""value"": ""Light Poisoned Purple"" }, { ""trait_type"": ""Torso"", ""value"": ""Ocean Blue"" }, { ""trait_type"": ""Left Arm"", ""value"": ""Rose Pink"" }, { ""trait_type"": ""Right Arm"", ""value"": ""Shadow Black"" }, { ""trait_type"": ""Left Leg"", ""value"": ""Algae Green"" }, { ""trait_type"": ""Right Leg"", ""value"": ""Nuclear Brown"" }, { ""trait_type"": ""Trade"", ""value"": ""Scribe"" }, { ""trait_type"": ""Background"", ""value"": ""Contaminated"" } ] }")]

        [TestCase("xrpamigos", "ipfs://bafybeihi4ampugzcwglbrfg52dxylscrl5saul4yv4fl2gms55o4vbxswq/1685508704460.png", @"{""attributes"":[],""collection"":{""name"":""xrpamigos"",""family"":""xrpamigos""},""video"":"""",""animation"":"""",""external_link"":"""",""audio"":"""",""name"":""xrpamigos #558"",""image"":""ipfs://bafybeihi4ampugzcwglbrfg52dxylscrl5saul4yv4fl2gms55o4vbxswq/1685508704460.png"",""taxon"":39233,""description"":"""",""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""id"":""b1642ca3-0a43-e980-d032-3ae75b04b8c7:1685508683106"",""file"":""""}")]

        [TestCase("OG POKER STARZ", "ipfs://ipfs/bafybeiepscron7uwe6hhgyyuq5ghyqg345efj4pr3lzifojc4r7ye5nbpi/image.jpeg", @"{""name"":""#13 POKER STAR - TIER 3"",""description"":""1 of 500 TIER 3 💎 Diamond Bones NFTs Tied To XRPokerStarz Decentralized POKER Community."",""external_url"":""https://xmart.art/profile/XRPokerStarz"",""attributes"":[{""trait_type"":""diamond_bones"",""value"":""TIER 3""},{""trait_type"":""og_poker_star"",""value"":1,""max_value"":1}],""category"":""art"",""md5hash"":""6cde017b78948b68542616dad029ce1c"",""is_explicit"":false,""content_type"":""image/png"",""image_url"":""ipfs://ipfs/bafybeiepscron7uwe6hhgyyuq5ghyqg345efj4pr3lzifojc4r7ye5nbpi/image.jpeg"",""animation_url"":""ipfs://ipfs/bafybeiepscron7uwe6hhgyyuq5ghyqg345efj4pr3lzifojc4r7ye5nbpi/animation.png""}")]

        [TestCase("Coreum Selects -Kings & Queens", "ipfs://ipfs/bafybeihkcggjl4ptjivdynqpxyllalixbfxnjmdf2yxbzwmiiysj3ovpae/image.jpeg", @"{""name"":""Coreum Selects 001"",""description"":""Coreum Selects (Kings &amp; Queens; 1st edition )\n\nThis super unique collection of NFTs will be limited to 25 only of the rarest NFTs on the XRPL, and has Royality written all over it.\n       This (Select) collection will have 25k Coreum Tokens staked and accruing rewards by me at time of launch, (locked for 60 months minimum) there will be no royalties on this collection, and all monies collected for the original sale, will go to buy and stake Coreum tokens, 100% of all rewards going to the holders. All rewards will be paid in Coreum 4 times per year or every 3 months. \n      When this collection is sold out it should have between 150k-200k Coreum staked for only 25 holders. \n        After the 60 months is up  the holders will have a one time decision to take the 25k Coreum I originally staked or 10% of the staked amout to split between them, or choose to let it ride.(my 25k  Coreum tokens will be unlocked if its not distributed between the holders) The NFTs will be sold as follows, (25) NFTs 1000 xrp each"",""external_url"":"""",""attributes"":[],""category"":""art"",""md5hash"":""c1d5dd6bf9d7b919fc5f516dbb4a4db9"",""is_explicit"":false,""content_type"":""image/png"",""image_url"":""ipfs://ipfs/bafybeihkcggjl4ptjivdynqpxyllalixbfxnjmdf2yxbzwmiiysj3ovpae/image.jpeg"",""animation_url"":""ipfs://ipfs/bafybeihkcggjl4ptjivdynqpxyllalixbfxnjmdf2yxbzwmiiysj3ovpae/animation.png""}")]

        [TestCase("Money Minded Apes #5", "ipfs://ipfs/bafybeicsb343k2kvu4dat4kxm7reb4yyjbvnvq7eaayhyfnqebo3eql2j4/image.jpeg", @"{""name"":""Money Minded Ape #1707"",""description"":""Money Minded Apes is a collection of tiny little apes living on the XRPL. As their name suggests, these bad boys are all about the Mula! Most of them have made a fortune in crypto, and a few are still waiting for their favorite coin to moon. Some are low-key, and others are flashy and like to show off.\n\nVisit [www.moneymindedapes.com](https:&#x2F;&#x2F;www.moneymindedapes.com&#x2F;) for more information."",""external_url"":""https://www.moneymindedapes.com/"",""attributes"":[{""trait_type"":""background"",""value"":""ORANGE""},{""trait_type"":""fur"",""value"":""DARK BROWN""},{""trait_type"":""clothes"",""value"":""BOTANICAL HOODIE""},{""trait_type"":""eyes"",""value"":""XRP GLASSES 4 RED""},{""trait_type"":""mouth"",""value"":""KISS PURPLE""},{""trait_type"":""headwear"",""value"":""TRUCKER HAT PURPLE""},{""trait_type"":""type"",""value"":""GENERATED""}],""category"":""collectibles"",""md5hash"":""4de64a9a50f859b3fa697d8cf548e610"",""is_explicit"":false,""content_type"":""image/png"",""image_url"":""ipfs://ipfs/bafybeicsb343k2kvu4dat4kxm7reb4yyjbvnvq7eaayhyfnqebo3eql2j4/image.jpeg"",""animation_url"":""ipfs://ipfs/bafybeicsb343k2kvu4dat4kxm7reb4yyjbvnvq7eaayhyfnqebo3eql2j4/animation.png""}")]

        [TestCase("Tessera", "ipfs://bafybeic6rbeemos42kpyu7iog5h5bzrvkmv3qljvjccih3tniivsx5iwt4", @"{ ""schema"": ""ipfs://bafkreidtjf2ihiwtptiyadjfmesplo555iy2jdcwhfr6hkenr2z3fvxn2y"", ""nftType"": ""art.v0"", ""name"": ""Tessera #25"", ""description"": ""Tessera is a collection of incrementally minted mosaics from digitized small tiles originally cut out of vintage children's book covers. These are the ageless icons of storytelling. A dress up party of favored characters."", ""image"": ""ipfs://bafybeic6rbeemos42kpyu7iog5h5bzrvkmv3qljvjccih3tniivsx5iwt4"", ""animation"": """", ""video"": """", ""audio"": """", ""3d_model"": """", ""collection"": { ""name"": ""Tessera"" }, ""attributes"": [ { ""trait_type"": ""Type"", ""value"": ""Original"" }, { ""trait_type"": ""Background"", ""value"": ""Beige"" }, { ""trait_type"": ""Skintone"", ""value"": ""Caramel"" }, { ""trait_type"": ""Mouth"", ""value"": ""Thin"" }, { ""trait_type"": ""Eyes"", ""value"": ""Hazel"" }, { ""trait_type"": ""Eyebrows"", ""value"": ""Thin"" }, { ""trait_type"": ""Clothing"", ""value"": ""Flight Suit"" }, { ""trait_type"": ""Accessories"", ""value"": ""None"" }, { ""trait_type"": ""Headwear"", ""value"": ""Flight Helmet"" }, { ""trait_type"": ""Filter"", ""value"": ""None"" } ], ""license"": ""None"" }")]

        [TestCase("Degens", "https://arweave.net/Ch1WkIbTO7l-ltO-Uiz9tYumbIbY74IRsSVlUOz-nTY/1574.png", @"{ ""name"": ""Degen #1574"", ""image"": ""https://arweave.net/Ch1WkIbTO7l-ltO-Uiz9tYumbIbY74IRsSVlUOz-nTY/1574.png"", ""collection"": { ""name"": ""Degens"", ""description"": ""2222 Degens immortalized themselves into the ledger as an experiment, free their mind to unlock their secrets..."", ""image"": ""https://arweave.net/TEqaL1jTidUxHZO9KXNBWed9bEvEH_PNWm9vgpDU6Zk"" }, ""attributes"": [ { ""trait_type"": ""Background"", ""value"": ""Yellow"" }, { ""trait_type"": ""Body"", ""value"": ""Grey Jacket"" }, { ""trait_type"": ""Face"", ""value"": ""Scar"" }, { ""trait_type"": ""Eyes"", ""value"": ""Varient Two"" }, { ""trait_type"": ""Mouth"", ""value"": ""Smirk"" }, { ""trait_type"": ""Head"", ""value"": ""Head Band"" } ] }")]

        [TestCase("The Multivers of Ghosted", "ipfs://bafkreiaraazo5f7qexilbtebbir3iztyb7zlh2ihwwja2kixzpnl5szhkm", @"{ ""schema"": ""ipfs://bafkreidtjf2ihiwtptiyadjfmesplo555iy2jdcwhfr6hkenr2z3fvxn2y"", ""nftType"": ""art.v0"", ""name"": ""#126 Fishstick"", ""description"": ""#126 Fishstick\n<The Multivers of Ghosted> \nPixel Art 32x32px <1000%>"", ""image"": ""ipfs://bafkreiaraazo5f7qexilbtebbir3iztyb7zlh2ihwwja2kixzpnl5szhkm"", ""animation"": """", ""video"": """", ""audio"": """", ""3d_model"": """", ""collection"": { ""name"": ""The Multivers of Ghosted"" }, ""attributes"": [ { ""trait_type"": ""Fishstick's Hat"", ""value"": ""Brown"" }, { ""trait_type"": ""Fishstick's Skin"", ""value"": ""Orange"" }, { ""trait_type"": ""Fishstick's Suit"", ""value"": ""Blue"" }, { ""trait_type"": ""Gun"", ""value"": ""Brown and Silver"" } ], ""license"": ""CC BY-ND"" }")]

        [TestCase("RCN CLUB CARDS", "QmS8wc1cc9fBMAN71i5dUaavL4Rcw4tvcKkgkRiPPVhebP", @"{""schema"":""https://xrpnft.com/metadata"",""nftType"":""xrpnft.com.v0"",""name"":""RCN CLUB CARD #108"",""external_link"":""https://nft-riddler.art"",""collection"":{""name"":""RCN CLUB CARDS"",""family"":""Art""},""description"":"""",""date"":1670666646954,""image"":""QmS8wc1cc9fBMAN71i5dUaavL4Rcw4tvcKkgkRiPPVhebP""}")]

        [TestCase("SpaceGirls", "ipfs://bafkreiepkrhr3tpi3pk2wo3kc22qjssqsetwmsfpznaqtbjuo6aee4fiiq", @"{ ""schema"": ""ipfs://bafkreidtjf2ihiwtptiyadjfmesplo555iy2jdcwhfr6hkenr2z3fvxn2y"", ""nftType"": ""art.v0"", ""name"": ""SpaceGirls 5546"", ""description"": ""SpaceGirls 5546"", ""image"": ""ipfs://bafkreiepkrhr3tpi3pk2wo3kc22qjssqsetwmsfpznaqtbjuo6aee4fiiq"", ""animation"": """", ""video"": """", ""audio"": """", ""3d_model"": """", ""collection"": { ""name"": ""SpaceGirls"" }, ""attributes"": [ { ""trait_type"": ""Name"", ""value"": ""Mia"" }, { ""trait_type"": ""Suit"", ""value"": ""Metallic / Brown"" }, { ""trait_type"": ""Shot"", ""value"": ""Upper"" } ], ""license"": ""None"" }")]

        [TestCase("xClown 5k collection", "https://bafybeicoqzhj4nff7jnakbatc7yhgxosekowplpx6bvdd7yajhbhjgdhs4.ipfs.w3s.link/1667166745351.png", @"{""attributes"":[{""description"":""Background"",""trait_type"":""Background"",""value"":""tawny""},{""description"":""Body"",""trait_type"":""Body"",""value"":""super tanned makeup""},{""description"":""Outfit"",""trait_type"":""Outfit"",""value"":""ghouls clown outfit""},{""description"":""Wig"",""trait_type"":""Wig"",""value"":""jester clown hat""},{""description"":""Eye"",""trait_type"":""Eye"",""value"":""bobo clown eyes""},{""description"":""Mouth"",""trait_type"":""Mouth"",""value"":""black mask""}],""collection"":{""name"":""xClown 5k collection"",""family"":""xClown""},""video"":"""",""animation"":"""",""external_link"":"""",""audio"":"""",""name"":""#4888"",""image"":""https://bafybeicoqzhj4nff7jnakbatc7yhgxosekowplpx6bvdd7yajhbhjgdhs4.ipfs.w3s.link/1667166745351.png"",""taxon"":18,""description"":""XCLOWN COLLECTION GEN1"",""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""id"":""acd0f91206b34a3fdcfd602a5a330b89:1667166745344"",""file"":""""}")]

        [TestCase("The Mad Monkeys", "ipfs://bafybeicyvvstdu7bshtcyvciwvydgalbwweeq6x3tiqh75tforjrviygza/24.png", @"{ ""name"": ""The Mad Monkeys #24"", ""description"": ""Beasty Bits are happy to introduce The Mad Monkeys living on XRPL.The Mad Monkey Genesis collection holders are immediate members of Beasty Bits club and unlock the possibility of Majestic Beast tier membership. Mad Monkeys holders receive each of the subsequent drops in Beasty Bits NFT series!."", ""image"": ""ipfs://bafybeicyvvstdu7bshtcyvciwvydgalbwweeq6x3tiqh75tforjrviygza/24.png"", ""dna"": ""173813538GTE24"", ""edition"": 24, ""external_url"": ""https://beastybits.com/"", ""attributes"": [ { ""trait_type"": ""Rank"", ""value"": 177 }, { ""trait_type"": ""Name"", ""value"": ""Henry"" }, { ""trait_type"": ""Class"", ""value"": ""Conscious"" }, { ""trait_type"": ""Collection#"", ""value"": ""1_1"" }, { ""trait_type"": ""Series#"", ""value"": ""1 (Genesis)"" } ], ""collection"": { ""family"": ""Beasty Bits"", ""name"": ""The Mad Monkeys"" }, ""compiler"": ""Beasty Bits"" }")]

        [TestCase("Famous Portrait Artists", "ipfs://ipfs/bafybeig7rgfhxtjtzue5ee7h3kmr57lmlqlasceywxdkjcoaqwyfoufary/image.jpeg", @"{""name"":""John Singer Sargent #2017"",""description"":""John Singer Sargent (1856-1925) was an American painter who spent most of his career in Europe, where he became known for his portraits of the wealthy and famous. He was born in Florence, Italy, to American parents, and spent much of his childhood traveling between Europe and the United States.\n\n\nSargent studied art in Paris under the renowned portrait painter Carolus-Duran, who had a strong influence on his style. Sargent&#x27;s portraits are known for their bravura brushwork, rich color, and ability to capture the personality and character of his subjects.\n\n\nIn addition to portraits, Sargent also painted landscapes and genre scenes. He was a prolific artist, and his work can be found in many museums and private collections around the world.\n\n\nSome of Sargent&#x27;s most famous works include &quot;Madame X,&quot; a portrait of a society beauty in a scandalous black dress, and &quot;The Daughters of Edward Darley Boit,&quot; a group portrait of four young girls in a dimly lit hallway.\n\n\nSargent was highly regarded by his contemporaries and was honored with many awards and accolades throughout his career. Today, he is considered one of the greatest portrait painters of all time."",""external_url"":""https://sologenic.org/nfts/rwJZxW8NKqmz5qH8yeRVa2aHi4JUeLHf7t"",""attributes"":[],""category"":""art"",""md5hash"":""db45672c32b31302a1b8e195389696b8"",""is_explicit"":false,""content_type"":""image/jpeg"",""protected_content"":{""encryptedText"":""w1oLHT6b/nHiCjxhvlKWahD2zvr8F/OI0ZKRw9IjpmKUe6+xx+4FMn9KGNBicp8ObPFrXAYwUCnDfnGt53qfHDoaurt7s29YbYF/E/UwM+gJ818bZEDqa9/DhwR1WBOc0jVsiPQ3ZldjFOqF5Q4OSZS+MhhFsepqK5lpM77N25Fy9dtA0UC/S7tBb2SBlfR8RVRX0qkbOfqrU0HJk0rtgPvbg69Ozlfq9uh1l+TPMMs46gebdcm5I0mksOwzDynvn6En87DFRA0aWFOA2ipA2/V+9Qt0mS7onAfVv805lR6ndtAGcz2jrFz75aruR3apQa5WU1hlDnDFIFWhwmaszTc1pEwE5s8kM9hMjOzEtNUhXOFUgcu/brUL2dMJp76lcKCig+xicPfH1L5FYat4i65ZvhEgRzz3/ZsWxBtjD0h32n2wgPH8GFM30YC/jxkhhCoWZYgsPbnKBtz7qKwK6hP9K/jKBm8lK2vyIBDR1qJMMQkygfRwKjelpIztN1T1v20/XzMmRCcmdcB5yRxCEIvLQ1iZ59MYM4ydXiKuKvngY+eNNTn3DCISFsQzSqA=""},""image_url"":""ipfs://ipfs/bafybeig7rgfhxtjtzue5ee7h3kmr57lmlqlasceywxdkjcoaqwyfoufary/image.jpeg"",""animation_url"":""ipfs://ipfs/bafybeig7rgfhxtjtzue5ee7h3kmr57lmlqlasceywxdkjcoaqwyfoufary/animation.jpeg""}")]

        [TestCase("Pixel X Pepes", "ipfs://bafybeib5dtg6oygau7kak7qvfwoxd2es57kb363skq25vdyawycbk5cgya/5859.png", @"{ ""name"": ""Pixel X Pepe #5859"", ""image"": ""ipfs://bafybeib5dtg6oygau7kak7qvfwoxd2es57kb363skq25vdyawycbk5cgya/5859.png"", ""collection"": { ""name"": ""Pixel X Pepes"", ""description"": ""Pixel X Pepes - An xPEPE gen 2 collection - Art by Link"", ""image"": ""ipfs://bafybeihkkdt3vqwagws53h5bksx2p5x5gmxgjkxqpadm2jcfhs3lyx3zyu"" }, ""attributes"": [ { ""trait_type"": ""Background"", ""value"": ""Purple"" }, { ""trait_type"": ""Base"", ""value"": ""Green"" }, { ""trait_type"": ""Hat"", ""value"": ""Purple Top Hat"" }, { ""trait_type"": ""Eye"", ""value"": ""Kermit"" }, { ""trait_type"": ""Shirt"", ""value"": ""White Robe"" }, { ""trait_type"": ""Mouth"", ""value"": ""Open Tongue Clown"" } ] }")]

        [TestCase("Lux Lions Private Gen 2 OG", "ipfs://bafybeihbha7hgf7uxrglntubigy4aq2ykfo5xmpb35wyomdgp6rlsleg2q/1677159196547.png", @"{""attributes"":[{""description"":""BACKGROUND"",""trait_type"":""BACKGROUND"",""value"":""Jungle""},{""description"":""SKIN"",""trait_type"":""SKIN"",""value"":""Lion_Skin""},{""description"":""CLOTHES"",""trait_type"":""CLOTHES"",""value"":""Lux_Lions_XRP_Life_Sweatshirt""},{""description"":""MANE"",""trait_type"":""MANE"",""value"":""Fire""},{""description"":""ACCESSORIES"",""trait_type"":""ACCESSORIES"",""value"":""Lux_Lion_Gold""},{""description"":""MOUTH"",""trait_type"":""MOUTH"",""value"":""Smile""},{""description"":""EYE"",""trait_type"":""EYE"",""value"":""Blue""},{""description"":""EYEWEAR"",""trait_type"":""EYEWEAR"",""value"":""XRP_Eyes""},{""description"":""HEADGEAR"",""trait_type"":""HEADGEAR"",""value"":""Lux_Lions_Baseball""}],""collection"":{""name"":""Lux Lions Private Gen 2 OG"",""family"":""Lux Lions""},""video"":"""",""animation"":"""",""external_link"":"""",""audio"":"""",""name"":""Lux Lions NFT #615"",""image"":""ipfs://bafybeihbha7hgf7uxrglntubigy4aq2ykfo5xmpb35wyomdgp6rlsleg2q/1677159196547.png"",""taxon"":7806,""description"":""To replace this description"",""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""id"":""f0c7817dffb2cf607b7392ac6eb61e76:1677159196438"",""file"":""""}")]

        [TestCase("pXycho Bunny", "ipfs://ipfs/bafybeih6ays5ilpnba2mfpmtg45vxxufuosc2mmwfeig46vcqny3bpsoke/image.jpeg", @"{""name"":""pXycho Bunny #359"",""description"":""pXycho Bunny are Handmade drawings\n\nEach pXycho Bunny is Unique 1&#x2F;1"",""external_url"":"""",""attributes"":[{""trait_type"":""pxycho_bunny"",""value"":1,""max_value"":1}],""category"":""art"",""md5hash"":""82d2281e1e2f154e3cc1b8aa1009ef51"",""is_explicit"":false,""content_type"":""image/png"",""image_url"":""ipfs://ipfs/bafybeih6ays5ilpnba2mfpmtg45vxxufuosc2mmwfeig46vcqny3bpsoke/image.jpeg"",""animation_url"":""ipfs://ipfs/bafybeih6ays5ilpnba2mfpmtg45vxxufuosc2mmwfeig46vcqny3bpsoke/animation.png""}")]

        [TestCase("METAPUNKS", "ipfs://bafybeihzypifvqyph7q7toblf6scykhvstqprbwx7qosu6s6mf7nbucnny", @"{ ""schema"": ""ipfs://bafkreidtjf2ihiwtptiyadjfmesplo555iy2jdcwhfr6hkenr2z3fvxn2y"", ""nftType"": ""art.v0"", ""name"": ""PUNKS 48"", ""description"": ""WE ARE PUNKS !"", ""image"": ""ipfs://bafybeihzypifvqyph7q7toblf6scykhvstqprbwx7qosu6s6mf7nbucnny"", ""animation"": """", ""video"": """", ""audio"": """", ""3d_model"": """", ""collection"": { ""name"": ""METAPUNKS"" }, ""attributes"": [ { ""trait_type"": ""HAIR"", ""value"": ""Black Frizzy"" }, { ""trait_type"": ""SKIN"", ""value"": ""Dark Brown"" }, { ""trait_type"": ""NECKLACE"", ""value"": ""Golden XRP"" }, { ""trait_type"": ""ACCESSORIES"", ""value"": ""Microphone"" }, { ""trait_type"": ""CLOTHES"", ""value"": ""Metal Top"" }, { ""trait_type"": ""BACKGROUND"", ""value"": ""Gray"" }, { ""trait_type"": ""TATTOO"", ""value"": ""Melody"" } ], ""license"": ""None"" }")]

        [TestCase("2inyhorse", "ipfs://QmTxWybeEU1ZEQNxe6KTAGEtCTjZcQbKMCJLpv1sRBJ8fp", @"{""schema"":""ipfs://bafkreidtjf2ihiwtptiyadjfmesplo555iy2jdcwhfr6hkenr2z3fvxn2y"",""nftType"":""art.v0"",""name"":""2inyhorse 1407"",""image"":""ipfs://QmTxWybeEU1ZEQNxe6KTAGEtCTjZcQbKMCJLpv1sRBJ8fp"",""description"":""https://thurstober.com"",""animation"":"""",""video"":"""",""audio"":"""",""3d_model"":"""",""collection"":{""name"":""2inyhorse""},""attributes"":[{""trait_type"":""Background"",""value"":""Amethyst""},{""trait_type"":""Coat Color"",""value"":""Royal""},{""trait_type"":""Coat Marking"",""value"":""Fawn""},{""trait_type"":""Hair Style"",""value"":""Windswept Raspberry""},{""trait_type"":""Accessory"",""value"":""All that glimmers is oat""},{""trait_type"":""Eyes"",""value"":""Normal""},{""trait_type"":""Mouth"",""value"":""Eee""},{""trait_type"":""Drop Theme"",""value"":""History""},{""trait_type"":""Animation Desc."",""value"":""N/A""},{""trait_type"":""Animation"",""value"":""No""}],""license"":""None""}")]

        [TestCase("XFLOKI ", "ipfs://QmaaGJgSpcVkfwkPL8UXQmUmUXJS5CoEbUwW2HgNjXhzpa", @"{ ""name"": ""XFLOKI PRIME EGG - The Beginning - Tier 4 #338"", ""description"": ""A finely minted XFLOKI PRIME EGG from our very own XFLOKIGEN on the XRP ledger! The Beginning Tier 4! #338"", ""image"": ""ipfs://QmaaGJgSpcVkfwkPL8UXQmUmUXJS5CoEbUwW2HgNjXhzpa"", ""external_url"": ""https://xflokiverse.com/"", ""attributes"": [ { ""trait_type"": ""Quality"", ""value"": ""Silver"" }, { ""trait_type"": ""HP"", ""value"": ""8110"" }, { ""trait_type"": ""Defense"", ""value"": ""8"" }, { ""trait_type"": ""Power"", ""value"": ""16543"" }, { ""trait_type"": ""Elemental"", ""value"": ""Earth"" }, { ""trait_type"": ""Critical Chance"", ""value"": ""4"" }, { ""trait_type"": ""Critical Damage"", ""value"": ""22"" }, { ""trait_type"": ""Block"", ""value"": ""4"" }, { ""trait_type"": ""Dodge"", ""value"": ""4"" }, { ""trait_type"": ""Speed"", ""value"": ""17"" } ], ""collection"": [ { ""family"": ""XFLOKI"", ""name"": ""XFLOKI PRIME EGG"" } ], ""edition"": ""1"", ""date"": ""1668756735000"", ""compiler"": ""XFLOKIVERSE"" }")]

        [TestCase("XFLOKI PRIME", "ipfs://QmeZUW488g2pKT87U1nb6d5JfZ1avEq2w17BmxxrQxpYaT", @"{ ""name"": ""XFLOKI PRIME - The Beginning - Tier 5 #556"", ""description"": ""A finely minted XFLOKI PRIME from our very own XFLOKIGEN on the XRP ledger! The Beginning Tier 5! #556"", ""image"": ""ipfs://QmeZUW488g2pKT87U1nb6d5JfZ1avEq2w17BmxxrQxpYaT"", ""external_url"": ""https://xflokiverse.com/"", ""attributes"": [ { ""trait_type"": ""Quality"", ""value"": ""Ruby"" }, { ""trait_type"": ""HP"", ""value"": ""16286"" }, { ""trait_type"": ""Defense"", ""value"": ""18"" }, { ""trait_type"": ""Power"", ""value"": ""29872"" }, { ""trait_type"": ""Elemental"", ""value"": ""Dark"" }, { ""trait_type"": ""Critical Chance"", ""value"": ""11"" }, { ""trait_type"": ""Critical Damage"", ""value"": ""50"" }, { ""trait_type"": ""Block"", ""value"": ""9"" }, { ""trait_type"": ""Dodge"", ""value"": ""8"" }, { ""trait_type"": ""Speed"", ""value"": ""108"" } ], ""collection"": [ { ""family"": ""XFLOKI"", ""name"": ""XFLOKI PRIME"" } ], ""edition"": ""1"", ""date"": ""1668756735000"", ""compiler"": ""XFLOKIVERSE"" }")]

        [TestCase("ZANIMALS OG", "https://bafybeicahyf72qlybifdifrhnj6gil5r522ditsfji2hnainp5gkkhtlga.ipfs.w3s.link/1669845455973.png", @"{""attributes"":[{""description"":""Original Mint Date"",""trait_type"":""Original Mint Date"",""value"":""23 Apr 2022""},{""description"":""Original Mint Marketplace"",""trait_type"":""Original Mint Marketplace"",""value"":""Sologenic""},{""description"":""Last Sale Price"",""trait_type"":""Last Sale Price"",""value"":""1200""},{""description"":""Orginal NFT Token ID"",""trait_type"":""Orginal NFT Token ID"",""value"":""023031516D4E50774E4654363836333700000000""},{""description"":""Original Issuer"",""trait_type"":""Original Issuer"",""value"":""rLZgCycFrdDgFQ5r5J44ZUgCUqvrLfYZUd""},{""description"":""Orginal XLS14 NFT URL"",""trait_type"":""Orginal XLS14 NFT URL"",""value"":""https://sologenic.org/nfts/rLZgCycFrdDgFQ5r5J44ZUgCUqvrLfYZUd/023031516D4E50774E4654363836333700000000""}],""collection"":{""name"":""ZANIMALS OG"",""family"":""ZANIMAL""},""video"":"""",""animation"":"""",""external_link"":"""",""audio"":"""",""name"":""ZANIMALS OG #51"",""image"":""https://bafybeicahyf72qlybifdifrhnj6gil5r522ditsfji2hnainp5gkkhtlga.ipfs.w3s.link/1669845455973.png"",""taxon"":373,""description"":"""",""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""id"":""e9733681c8de3fe69b71e8d12c2f9ba7:1669845455865"",""file"":""""}")]

        // Video not supported
        [TestCase("XRP Rain Dancers", null, @"{""attributes"":[{""description"":""Glass Sheen"",""trait_type"":""Glass Sheen"",""value"":""Blue""},{""description"":""Song"",""trait_type"":""Song"",""value"":""XRPaid""},{""description"":""Background"",""trait_type"":""Background"",""value"":""Burnt Orange""},{""description"":""Dance"",""trait_type"":""Dance"",""value"":""Boogaloo""},{""description"":""Rain Dancer"",""trait_type"":""Rain Dancer"",""value"":""Crypto Eri""},{""description"":""Glass Color"",""trait_type"":""Glass Color"",""value"":""Orange""},{""description"":""Glass"",""trait_type"":""Glass"",""value"":""Xumm Logo""},{""description"":""Flair"",""trait_type"":""Flair"",""value"":""Diamond""}],""collection"":{""name"":""XRP Rain Dancers"",""family"":""Good Times""},""video"":""ipfs://bafybeie3dgishu7s4snossygje3qu7psyzvmosvjwcqpu2vy6xil5nh45a/1679078647786.mp4"",""animation"":"""",""external_link"":"""",""audio"":"""",""name"":""Rain Dancer #73"",""image"":"""",""taxon"":253,""description"":""NOTE - You may need to click on \""View NFT\"" at the bottom of the page to see the full animation with music.\\n\\nIndividually crafted 3D animations of our favorite XRP influencers, Ripple employees, and community members dancing in good fortunes for the XRP Army 🕺🎵💃☔🕺🎵💃☔🕺🎵💃☔\\n\\nOwners can also earn our daily discord currency, Smile Coin, which can be used to purchase NFTs, IRL items, raffles, merch, Augmented Reality art, and more!"",""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""id"":""4db0d755-0f9a-77e0-6456-38554fc0321a:1679078623600"",""file"":""""}")]

        [TestCase("CryptoniaX", "ipfs://bafybeiaoy3rjemlvomapczqnkhbl3e4wveoycixyii5vkhi5mpkhxri62a/1688034187793.png", @"{""attributes"":[{""description"":""Backgrounds"",""trait_type"":""Backgrounds"",""value"":""Songbird""},{""description"":""Skin"",""trait_type"":""Skin"",""value"":""Grey""},{""description"":""Clothes"",""trait_type"":""Clothes"",""value"":""Cardano jacket""},{""description"":""Eyes"",""trait_type"":""Eyes"",""value"":""Hypnotized 3""},{""description"":""Sunglasses"",""trait_type"":""Sunglasses"",""value"":""Heart glasses""},{""description"":""Head"",""trait_type"":""Head"",""value"":""Brown""},{""description"":""Mouth"",""trait_type"":""Mouth"",""value"":""XRP nail""},{""description"":""Earrings"",""trait_type"":""Earrings"",""value"":""Staples""},{""description"":""Hand"",""trait_type"":""Hand"",""value"":""Heart""}],""collection"":{""name"":""CryptoniaX"",""family"":""CryptoniaX""},""video"":"""",""animation"":"""",""external_link"":"""",""audio"":"""",""name"":""CryptoniaX #6722"",""image"":""ipfs://bafybeiaoy3rjemlvomapczqnkhbl3e4wveoycixyii5vkhi5mpkhxri62a/1688034187793.png"",""taxon"":48047,""description"":""Cryptoniax is a thriving NFT collection designed specifically for crypto enthusiasts. Owning one or more NFTs from Cryptoniax grants unique advantages and utility to its holders, fostering an engaging and rewarding experience within the community."",""schema"":""ipfs://QmNpi8rcXEkohca8iXu7zysKKSJYqCvBJn3xJwga8jXqWU"",""nftType"":""art.v0"",""id"":""42c2c9d7b25791c0984b2b70d7bb3ea2:1688034187771"",""file"":""""}")]

        [TestCase("DexBorg Collection", "ipfs://ipfs/bafybeidcvyphxw4slscldojtbe3kdxv36cttuswrmswhkehyf6jn7bulhu/image.jpeg", @"{""name"":""DexBorg #0005"",""description"":""Join the XRPL Dex with the most reliable trading partner - DexBorg! Adopt this faithful and cute borg today and enjoy the benefits of having a loyal and powerful companion by your side. DexBorg&#x27;s unwavering dedication and loyalty will ensure a successful trading experience while adding a touch of excitement to your day. Don&#x27;t miss out on this opportunity to enhance your trading game with the best companion around. Get DexBorg today and discover the joys of trading on XRPL Dex."",""external_url"":""https://coolscreeners.net/DEXMachine/"",""attributes"":[{""trait_type"":""dexborg"",""value"":5,""max_value"":9999}],""category"":""others"",""md5hash"":""5d7caed47fc355aa47533e7a172f856c"",""is_explicit"":false,""content_type"":""image/png"",""image_url"":""ipfs://ipfs/bafybeidcvyphxw4slscldojtbe3kdxv36cttuswrmswhkehyf6jn7bulhu/image.jpeg"",""animation_url"":""ipfs://ipfs/bafybeidcvyphxw4slscldojtbe3kdxv36cttuswrmswhkehyf6jn7bulhu/animation.png""}")]

        [TestCase("XRP mfers", "ipfs://bafkreigyv6w6fkkguoitj6lpxn44in3mmpgwicu7q2et6hnn2o73ljkhvi", @"{ ""schema"": ""ipfs://bafkreidtjf2ihiwtptiyadjfmesplo555iy2jdcwhfr6hkenr2z3fvxn2y"", ""nftType"": ""art.v0"", ""name"": ""XRPMFER #196"", ""description"": ""mfers on the XRP Ledger. They have 'Derivative blue' properties and share the same attributes as their siblings on Ethereum."", ""image"": ""ipfs://bafkreigyv6w6fkkguoitj6lpxn44in3mmpgwicu7q2et6hnn2o73ljkhvi"", ""animation"": """", ""video"": """", ""audio"": """", ""collection"": { ""name"": ""XRP mfers"" }, ""attributes"": [], ""license"": ""None"" }")]

        [TestCase("Zerpaay's Elite Colonels", "ipfs://bafybeiae6j47dgpxcehwuyouw4w6d5coxsx3dnibv6meezg7brn6eif6mu/thumbnail.jpg", @"{ ""name"": ""Colonel #28"", ""image"": ""ipfs://bafybeiae6j47dgpxcehwuyouw4w6d5coxsx3dnibv6meezg7brn6eif6mu/thumbnail.jpg"", ""video"": ""ipfs://bafybeiae6j47dgpxcehwuyouw4w6d5coxsx3dnibv6meezg7brn6eif6mu/video.mp4"", ""collection"": { ""name"": ""Zerpaay's Elite Colonels"", ""family"": ""Zerpaay The Shar Pei"", ""description"": ""Brace yourself for an explosion of excitement! Introducing Zerpaay's Elite Colonels\u2014the limited edition, strategy-driven NFTs that don't just make you stand out, but make you feel unique too! This isn't just another collection; it's your exclusive pass into the inner circle of Zerpaay's Elite Colonel Brigade."", ""image"": ""ipfs://bafybeic4opkbosca3tmyswajifrg3g6g7ar3abxlup5avxlax2thujxx2q/pfp.png"" }, ""attributes"": [ { ""trait_type"": ""Rank"", ""value"": ""Colonel"" } ] }")]

        [TestCase("BearableGuyClub Genesis I", "ipfs://bafybeifv3ojnoafdueok42bqsqti6ijf2fpv4y3gtrtjzm6ih6c7iujrx4/386.png", @"{ ""name"": ""BearableGuy #386"", ""description"": ""NO AFFILIATION to the original bearableguy123 riddler we all love. BearableGuyClub is an NFT community that enjoys XRP researchers and riddlers."", ""image"": ""ipfs://bafybeifv3ojnoafdueok42bqsqti6ijf2fpv4y3gtrtjzm6ih6c7iujrx4/386.png"", ""file_url"": ""ipfs://bafybeifv3ojnoafdueok42bqsqti6ijf2fpv4y3gtrtjzm6ih6c7iujrx4/386.png"", ""image_url"": ""ipfs://bafybeifv3ojnoafdueok42bqsqti6ijf2fpv4y3gtrtjzm6ih6c7iujrx4/386.png"", ""animation_url"": ""ipfs://bafybeifv3ojnoafdueok42bqsqti6ijf2fpv4y3gtrtjzm6ih6c7iujrx4/386.png"", ""category"": ""art"", ""content_type"": ""image/png"", ""collection"": { ""family"": ""BearableGuyClub"", ""name"": ""BearableGuyClub Genesis I"" }, ""attributes"": [ { ""trait_type"": ""Background"", ""value"": ""Orange"" }, { ""trait_type"": ""Body"", ""value"": ""Kermode"" }, { ""trait_type"": ""Dress"", ""value"": ""KingBlue"" }, { ""trait_type"": ""Mouth"", ""value"": ""Grin"" }, { ""trait_type"": ""Eye"", ""value"": ""Downview"" }, { ""trait_type"": ""Mask"", ""value"": ""Wing"" }, { ""trait_type"": ""Hat"", ""value"": ""Donald"" }, { ""trait_type"": ""Role"", ""value"": ""Genesis"" } ], ""external_url"": ""https://bearableguy.club"", ""edition"": 386, ""date"": 1667174400000, ""compiler"": ""BearableGuyClub Team"" }")]

        [TestCase("Raising Men and Women", "ipfs://ipfs/bafybeialm3autnpqz3mxfie4we4w4vibkvfangamcslf4kmspccemi3zny/image.jpeg", @"{""name"":""Raising Men and Women #4"",""description"":""This NFT series was made to benefit Raising Men and Women Lawn Care and pays a passive income to the NFT holders.  Additional utility may be added later if decided by the Ark team\n\nArt by ARK Institute Co-Founder Rich Greeley (BaconBitz)\n\nARK Website: https:&#x2F;&#x2F;www.ark.institute&#x2F;\n\nRMW Website: http:&#x2F;&#x2F;raisingmenandwomenlawncare.com&#x2F;"",""external_url"":""https://www.ark.institute/"",""attributes"":[],""category"":""collectibles"",""md5hash"":""637fda9f3dfa931844ddf42510ed8c11"",""is_explicit"":false,""content_type"":""image/jpeg"",""image_url"":""ipfs://ipfs/bafybeialm3autnpqz3mxfie4we4w4vibkvfangamcslf4kmspccemi3zny/image.jpeg"",""animation_url"":""ipfs://ipfs/bafybeialm3autnpqz3mxfie4we4w4vibkvfangamcslf4kmspccemi3zny/animation.jpeg""}")]

        [TestCase("XMEME COLLECTION #1", "ipfs://bafkreihnrr4y4e4bc5yadiwda4hfqpoy2ywbjf4ggz4kcictwmi4c7l7pi", @"{ ""schema"": ""ipfs://bafkreidtjf2ihiwtptiyadjfmesplo555iy2jdcwhfr6hkenr2z3fvxn2y"", ""nftType"": ""art.v0"", ""name"": ""XMEME OG MEMBER BADGE #3"", ""description"": ""Only 50 OG badges will ever exist. XMEME is different"", ""image"": ""ipfs://bafkreihnrr4y4e4bc5yadiwda4hfqpoy2ywbjf4ggz4kcictwmi4c7l7pi"", ""animation"": """", ""video"": """", ""audio"": """", ""3d_model"": """", ""collection"": { ""name"": ""XMEME COLLECTION #1"" }, ""attributes"": [], ""license"": ""None"" }")]

        public async Task Given_150To_200NFT_ReturnsImageAsync(
            string projectName,
            string image,
            string metaJson)
        {
            // Arrange
            // Not testing link to metadata for these, so set to anything
            // and return mock meta json anyway
            Token.URI = TestConstants.MetaNormalisedIpfsUrl;
            _mockHttpFacade.GetData(TestConstants.MetaNormalisedIpfsUrl).Returns(metaJson);

            // Act
            var result = await _classUnderTest.ProcessNFToken(Token);

            // Assert
            Assert.That(result, Is.EqualTo(image), message: projectName);
        }
    }
}
