name: Build and Package

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies main
      working-directory: ./UniversalNFT.dev.API
      run: dotnet restore

    - name: Install dependencies test project
      working-directory: ./UniversalNFT.dev.API.Tests
      run: dotnet restore

    # Execute all unit tests in the solution
    - name: Execute unit tests
      working-directory: ./UniversalNFT.dev.API.Tests
      run: dotnet test
